// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package environment

import (
	"github.com/go-faster/errors"
)

// 创建 Environment 的请求体。.
// Ref: #/components/schemas/CreateEnvironmentRequest
type CreateEnvironmentRequest struct {
	// 人类可读名称。.
	Name string `json:"name"`
	// 运行环境配置。.
	Config OptEnvConfig `json:"config"`
	// 描述信息。.
	Description OptString `json:"description"`
	// 用户自定义键值对元数据。.
	Metadata OptCreateEnvironmentRequestMetadata `json:"metadata"`
	// 一期未启用；仅协议占位。.
	Scope OptEnvironmentScope `json:"scope"`
}

// GetName returns the value of Name.
func (s *CreateEnvironmentRequest) GetName() string {
	return s.Name
}

// GetConfig returns the value of Config.
func (s *CreateEnvironmentRequest) GetConfig() OptEnvConfig {
	return s.Config
}

// GetDescription returns the value of Description.
func (s *CreateEnvironmentRequest) GetDescription() OptString {
	return s.Description
}

// GetMetadata returns the value of Metadata.
func (s *CreateEnvironmentRequest) GetMetadata() OptCreateEnvironmentRequestMetadata {
	return s.Metadata
}

// GetScope returns the value of Scope.
func (s *CreateEnvironmentRequest) GetScope() OptEnvironmentScope {
	return s.Scope
}

// SetName sets the value of Name.
func (s *CreateEnvironmentRequest) SetName(val string) {
	s.Name = val
}

// SetConfig sets the value of Config.
func (s *CreateEnvironmentRequest) SetConfig(val OptEnvConfig) {
	s.Config = val
}

// SetDescription sets the value of Description.
func (s *CreateEnvironmentRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetMetadata sets the value of Metadata.
func (s *CreateEnvironmentRequest) SetMetadata(val OptCreateEnvironmentRequestMetadata) {
	s.Metadata = val
}

// SetScope sets the value of Scope.
func (s *CreateEnvironmentRequest) SetScope(val OptEnvironmentScope) {
	s.Scope = val
}

// 用户自定义键值对元数据。.
type CreateEnvironmentRequestMetadata map[string]string

func (s *CreateEnvironmentRequestMetadata) init() CreateEnvironmentRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Delete Environment 响应体。.
// Ref: #/components/schemas/DeleteEnvironmentResponse
type DeleteEnvironmentResponse struct {
	// 被删除的 Environment ID。.
	ID string `json:"id"`
	// 对象类型标识。.
	Type string `json:"type"`
}

// GetID returns the value of ID.
func (s *DeleteEnvironmentResponse) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *DeleteEnvironmentResponse) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *DeleteEnvironmentResponse) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *DeleteEnvironmentResponse) SetType(val string) {
	s.Type = val
}

// Environment 的运行环境配置。按 `type` 区分 cloud / self_hosted。.
// Ref: #/components/schemas/EnvConfig
type EnvConfig struct {
	// 运行环境类型。.
	Type EnvConfigType `json:"type"`
	// 容器出网策略。.
	Networking OptNetworkingConfig `json:"networking"`
	// 启动时预装的依赖包。.
	Packages OptPackagesConfig `json:"packages"`
	// 容器启动时注入的环境变量。.
	Env OptEnvConfigEnv `json:"env"`
	// 沙箱启动阶段执行的初始化脚本。.
	SetupScript OptString `json:"setup_script"`
	// Environment outputs 的 TOS 存储配置。.
	Tos OptTosConfig `json:"tos"`
}

// GetType returns the value of Type.
func (s *EnvConfig) GetType() EnvConfigType {
	return s.Type
}

// GetNetworking returns the value of Networking.
func (s *EnvConfig) GetNetworking() OptNetworkingConfig {
	return s.Networking
}

// GetPackages returns the value of Packages.
func (s *EnvConfig) GetPackages() OptPackagesConfig {
	return s.Packages
}

// GetEnv returns the value of Env.
func (s *EnvConfig) GetEnv() OptEnvConfigEnv {
	return s.Env
}

// GetSetupScript returns the value of SetupScript.
func (s *EnvConfig) GetSetupScript() OptString {
	return s.SetupScript
}

// GetTos returns the value of Tos.
func (s *EnvConfig) GetTos() OptTosConfig {
	return s.Tos
}

// SetType sets the value of Type.
func (s *EnvConfig) SetType(val EnvConfigType) {
	s.Type = val
}

// SetNetworking sets the value of Networking.
func (s *EnvConfig) SetNetworking(val OptNetworkingConfig) {
	s.Networking = val
}

// SetPackages sets the value of Packages.
func (s *EnvConfig) SetPackages(val OptPackagesConfig) {
	s.Packages = val
}

// SetEnv sets the value of Env.
func (s *EnvConfig) SetEnv(val OptEnvConfigEnv) {
	s.Env = val
}

// SetSetupScript sets the value of SetupScript.
func (s *EnvConfig) SetSetupScript(val OptString) {
	s.SetupScript = val
}

// SetTos sets the value of Tos.
func (s *EnvConfig) SetTos(val OptTosConfig) {
	s.Tos = val
}

// 容器启动时注入的环境变量。.
type EnvConfigEnv map[string]string

func (s *EnvConfigEnv) init() EnvConfigEnv {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Environment 运行环境类型。.
// Ref: #/components/schemas/EnvConfigType
type EnvConfigType string

const (
	EnvConfigTypeCloud      EnvConfigType = "cloud"
	EnvConfigTypeSelfHosted EnvConfigType = "self_hosted"
)

// AllValues returns all EnvConfigType values.
func (EnvConfigType) AllValues() []EnvConfigType {
	return []EnvConfigType{
		EnvConfigTypeCloud,
		EnvConfigTypeSelfHosted,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EnvConfigType) MarshalText() ([]byte, error) {
	switch s {
	case EnvConfigTypeCloud:
		return []byte(s), nil
	case EnvConfigTypeSelfHosted:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EnvConfigType) UnmarshalText(data []byte) error {
	switch EnvConfigType(data) {
	case EnvConfigTypeCloud:
		*s = EnvConfigTypeCloud
		return nil
	case EnvConfigTypeSelfHosted:
		*s = EnvConfigTypeSelfHosted
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ARK Managed Agents 控制面 Environment 资源。.
// Ref: #/components/schemas/Environment
type Environment struct {
	// Environment ID。.
	ID string `json:"id"`
	// 固定 `"environment"`。.
	Type EnvironmentType `json:"type"`
	// 人类可读名称。.
	Name string `json:"name"`
	// 描述信息。.
	Description OptString `json:"description"`
	// 运行环境配置。.
	Config OptEnvConfig `json:"config"`
	// 用户自定义键值对元数据。.
	Metadata OptEnvironmentMetadata `json:"metadata"`
	// 一期未启用；仅协议占位。.
	Scope OptEnvironmentScope `json:"scope"`
	// RFC 3339 时间。.
	CreatedAt string `json:"created_at"`
	// RFC 3339 时间。.
	UpdatedAt string `json:"updated_at"`
	// Session 使用 EnvironmentWithOverrides 时，本次被覆写的 config 子字段。.
	OverriddenFields []string `json:"overridden_fields"`
}

// GetID returns the value of ID.
func (s *Environment) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *Environment) GetType() EnvironmentType {
	return s.Type
}

// GetName returns the value of Name.
func (s *Environment) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Environment) GetDescription() OptString {
	return s.Description
}

// GetConfig returns the value of Config.
func (s *Environment) GetConfig() OptEnvConfig {
	return s.Config
}

// GetMetadata returns the value of Metadata.
func (s *Environment) GetMetadata() OptEnvironmentMetadata {
	return s.Metadata
}

// GetScope returns the value of Scope.
func (s *Environment) GetScope() OptEnvironmentScope {
	return s.Scope
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Environment) GetCreatedAt() string {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Environment) GetUpdatedAt() string {
	return s.UpdatedAt
}

// GetOverriddenFields returns the value of OverriddenFields.
func (s *Environment) GetOverriddenFields() []string {
	return s.OverriddenFields
}

// SetID sets the value of ID.
func (s *Environment) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *Environment) SetType(val EnvironmentType) {
	s.Type = val
}

// SetName sets the value of Name.
func (s *Environment) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Environment) SetDescription(val OptString) {
	s.Description = val
}

// SetConfig sets the value of Config.
func (s *Environment) SetConfig(val OptEnvConfig) {
	s.Config = val
}

// SetMetadata sets the value of Metadata.
func (s *Environment) SetMetadata(val OptEnvironmentMetadata) {
	s.Metadata = val
}

// SetScope sets the value of Scope.
func (s *Environment) SetScope(val OptEnvironmentScope) {
	s.Scope = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Environment) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Environment) SetUpdatedAt(val string) {
	s.UpdatedAt = val
}

// SetOverriddenFields sets the value of OverriddenFields.
func (s *Environment) SetOverriddenFields(val []string) {
	s.OverriddenFields = val
}

// 用户自定义键值对元数据。.
type EnvironmentMetadata map[string]string

func (s *EnvironmentMetadata) init() EnvironmentMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Environment 作用域。一期未启用；仅协议占位。.
// Ref: #/components/schemas/EnvironmentScope
type EnvironmentScope string

const (
	EnvironmentScopeOrganization EnvironmentScope = "organization"
	EnvironmentScopeAccount      EnvironmentScope = "account"
)

// AllValues returns all EnvironmentScope values.
func (EnvironmentScope) AllValues() []EnvironmentScope {
	return []EnvironmentScope{
		EnvironmentScopeOrganization,
		EnvironmentScopeAccount,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EnvironmentScope) MarshalText() ([]byte, error) {
	switch s {
	case EnvironmentScopeOrganization:
		return []byte(s), nil
	case EnvironmentScopeAccount:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EnvironmentScope) UnmarshalText(data []byte) error {
	switch EnvironmentScope(data) {
	case EnvironmentScopeOrganization:
		*s = EnvironmentScopeOrganization
		return nil
	case EnvironmentScopeAccount:
		*s = EnvironmentScopeAccount
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// 固定 `"environment"`。.
type EnvironmentType string

const (
	EnvironmentTypeEnvironment EnvironmentType = "environment"
)

// AllValues returns all EnvironmentType values.
func (EnvironmentType) AllValues() []EnvironmentType {
	return []EnvironmentType{
		EnvironmentTypeEnvironment,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EnvironmentType) MarshalText() ([]byte, error) {
	switch s {
	case EnvironmentTypeEnvironment:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EnvironmentType) UnmarshalText(data []byte) error {
	switch EnvironmentType(data) {
	case EnvironmentTypeEnvironment:
		*s = EnvironmentTypeEnvironment
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Heartbeat work 的响应体。.
// Ref: #/components/schemas/HeartbeatWorkResponse
type HeartbeatWorkResponse struct {
	// 控制面接受的 heartbeat 时间，RFC 3339。.
	LastHeartbeat string `json:"last_heartbeat"`
	// Lease 是否被刷新。.
	LeaseExtended bool `json:"lease_extended"`
	// Work 生命周期状态。.
	State WorkState `json:"state"`
	// Lease TTL 秒数。.
	TTLSeconds int64 `json:"ttl_seconds"`
	// 对象类型，固定为 `work_heartbeat`。.
	Type HeartbeatWorkResponseType `json:"type"`
}

// GetLastHeartbeat returns the value of LastHeartbeat.
func (s *HeartbeatWorkResponse) GetLastHeartbeat() string {
	return s.LastHeartbeat
}

// GetLeaseExtended returns the value of LeaseExtended.
func (s *HeartbeatWorkResponse) GetLeaseExtended() bool {
	return s.LeaseExtended
}

// GetState returns the value of State.
func (s *HeartbeatWorkResponse) GetState() WorkState {
	return s.State
}

// GetTTLSeconds returns the value of TTLSeconds.
func (s *HeartbeatWorkResponse) GetTTLSeconds() int64 {
	return s.TTLSeconds
}

// GetType returns the value of Type.
func (s *HeartbeatWorkResponse) GetType() HeartbeatWorkResponseType {
	return s.Type
}

// SetLastHeartbeat sets the value of LastHeartbeat.
func (s *HeartbeatWorkResponse) SetLastHeartbeat(val string) {
	s.LastHeartbeat = val
}

// SetLeaseExtended sets the value of LeaseExtended.
func (s *HeartbeatWorkResponse) SetLeaseExtended(val bool) {
	s.LeaseExtended = val
}

// SetState sets the value of State.
func (s *HeartbeatWorkResponse) SetState(val WorkState) {
	s.State = val
}

// SetTTLSeconds sets the value of TTLSeconds.
func (s *HeartbeatWorkResponse) SetTTLSeconds(val int64) {
	s.TTLSeconds = val
}

// SetType sets the value of Type.
func (s *HeartbeatWorkResponse) SetType(val HeartbeatWorkResponseType) {
	s.Type = val
}

// 对象类型，固定为 `work_heartbeat`。.
type HeartbeatWorkResponseType string

const (
	HeartbeatWorkResponseTypeWorkHeartbeat HeartbeatWorkResponseType = "work_heartbeat"
)

// AllValues returns all HeartbeatWorkResponseType values.
func (HeartbeatWorkResponseType) AllValues() []HeartbeatWorkResponseType {
	return []HeartbeatWorkResponseType{
		HeartbeatWorkResponseTypeWorkHeartbeat,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HeartbeatWorkResponseType) MarshalText() ([]byte, error) {
	switch s {
	case HeartbeatWorkResponseTypeWorkHeartbeat:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HeartbeatWorkResponseType) UnmarshalText(data []byte) error {
	switch HeartbeatWorkResponseType(data) {
	case HeartbeatWorkResponseTypeWorkHeartbeat:
		*s = HeartbeatWorkResponseTypeWorkHeartbeat
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// List Environments 响应体。.
// Ref: #/components/schemas/ListEnvironmentsResponse
type ListEnvironmentsResponse struct {
	// 本页 Environment 列表。.
	Data []Environment `json:"data"`
	// 下一页 cursor（opaque）。
	// - 存在 → 还有更多数据，把此值作为下次请求的 `page` 参数
	// - 不存在 → 已列尽.
	NextPage OptString `json:"next_page"`
}

// GetData returns the value of Data.
func (s *ListEnvironmentsResponse) GetData() []Environment {
	return s.Data
}

// GetNextPage returns the value of NextPage.
func (s *ListEnvironmentsResponse) GetNextPage() OptString {
	return s.NextPage
}

// SetData sets the value of Data.
func (s *ListEnvironmentsResponse) SetData(val []Environment) {
	s.Data = val
}

// SetNextPage sets the value of NextPage.
func (s *ListEnvironmentsResponse) SetNextPage(val OptString) {
	s.NextPage = val
}

// 容器出网策略。.
// Ref: #/components/schemas/NetworkingConfig
type NetworkingConfig struct {
	// 出网策略类型。.
	Type NetworkingType `json:"type"`
	// 是否允许出网到 Environment/session 关联的 MCP servers。.
	AllowMcpServers OptBool `json:"allow_mcp_servers"`
	// 是否允许出网到常见包管理器 (pip / apt / npm 等) 的官方镜像。.
	AllowPackageManagers OptBool `json:"allow_package_managers"`
	// 显式允许的出网域名列表；`limited` 模式下与 `allow_*` 白名单叠加生效。
	// 未设置时仅走 `allow_*` 语义控制。.
	AllowedHosts []string `json:"allowed_hosts"`
}

// GetType returns the value of Type.
func (s *NetworkingConfig) GetType() NetworkingType {
	return s.Type
}

// GetAllowMcpServers returns the value of AllowMcpServers.
func (s *NetworkingConfig) GetAllowMcpServers() OptBool {
	return s.AllowMcpServers
}

// GetAllowPackageManagers returns the value of AllowPackageManagers.
func (s *NetworkingConfig) GetAllowPackageManagers() OptBool {
	return s.AllowPackageManagers
}

// GetAllowedHosts returns the value of AllowedHosts.
func (s *NetworkingConfig) GetAllowedHosts() []string {
	return s.AllowedHosts
}

// SetType sets the value of Type.
func (s *NetworkingConfig) SetType(val NetworkingType) {
	s.Type = val
}

// SetAllowMcpServers sets the value of AllowMcpServers.
func (s *NetworkingConfig) SetAllowMcpServers(val OptBool) {
	s.AllowMcpServers = val
}

// SetAllowPackageManagers sets the value of AllowPackageManagers.
func (s *NetworkingConfig) SetAllowPackageManagers(val OptBool) {
	s.AllowPackageManagers = val
}

// SetAllowedHosts sets the value of AllowedHosts.
func (s *NetworkingConfig) SetAllowedHosts(val []string) {
	s.AllowedHosts = val
}

// 容器出网策略。.
// Ref: #/components/schemas/NetworkingType
type NetworkingType string

const (
	NetworkingTypeUnrestricted NetworkingType = "unrestricted"
	NetworkingTypeLimited      NetworkingType = "limited"
)

// AllValues returns all NetworkingType values.
func (NetworkingType) AllValues() []NetworkingType {
	return []NetworkingType{
		NetworkingTypeUnrestricted,
		NetworkingTypeLimited,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s NetworkingType) MarshalText() ([]byte, error) {
	switch s {
	case NetworkingTypeUnrestricted:
		return []byte(s), nil
	case NetworkingTypeLimited:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *NetworkingType) UnmarshalText(data []byte) error {
	switch NetworkingType(data) {
	case NetworkingTypeUnrestricted:
		*s = NetworkingTypeUnrestricted
		return nil
	case NetworkingTypeLimited:
		*s = NetworkingTypeLimited
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateEnvironmentRequestMetadata returns new OptCreateEnvironmentRequestMetadata with value set to v.
func NewOptCreateEnvironmentRequestMetadata(v CreateEnvironmentRequestMetadata) OptCreateEnvironmentRequestMetadata {
	return OptCreateEnvironmentRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptCreateEnvironmentRequestMetadata is optional CreateEnvironmentRequestMetadata.
type OptCreateEnvironmentRequestMetadata struct {
	Value CreateEnvironmentRequestMetadata
	Set   bool
}

// IsSet returns true if OptCreateEnvironmentRequestMetadata was set.
func (o OptCreateEnvironmentRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateEnvironmentRequestMetadata) Reset() {
	var v CreateEnvironmentRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateEnvironmentRequestMetadata) SetTo(v CreateEnvironmentRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateEnvironmentRequestMetadata) Get() (v CreateEnvironmentRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateEnvironmentRequestMetadata) Or(d CreateEnvironmentRequestMetadata) CreateEnvironmentRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEnvConfig returns new OptEnvConfig with value set to v.
func NewOptEnvConfig(v EnvConfig) OptEnvConfig {
	return OptEnvConfig{
		Value: v,
		Set:   true,
	}
}

// OptEnvConfig is optional EnvConfig.
type OptEnvConfig struct {
	Value EnvConfig
	Set   bool
}

// IsSet returns true if OptEnvConfig was set.
func (o OptEnvConfig) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEnvConfig) Reset() {
	var v EnvConfig
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEnvConfig) SetTo(v EnvConfig) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEnvConfig) Get() (v EnvConfig, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEnvConfig) Or(d EnvConfig) EnvConfig {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEnvConfigEnv returns new OptEnvConfigEnv with value set to v.
func NewOptEnvConfigEnv(v EnvConfigEnv) OptEnvConfigEnv {
	return OptEnvConfigEnv{
		Value: v,
		Set:   true,
	}
}

// OptEnvConfigEnv is optional EnvConfigEnv.
type OptEnvConfigEnv struct {
	Value EnvConfigEnv
	Set   bool
}

// IsSet returns true if OptEnvConfigEnv was set.
func (o OptEnvConfigEnv) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEnvConfigEnv) Reset() {
	var v EnvConfigEnv
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEnvConfigEnv) SetTo(v EnvConfigEnv) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEnvConfigEnv) Get() (v EnvConfigEnv, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEnvConfigEnv) Or(d EnvConfigEnv) EnvConfigEnv {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEnvironmentMetadata returns new OptEnvironmentMetadata with value set to v.
func NewOptEnvironmentMetadata(v EnvironmentMetadata) OptEnvironmentMetadata {
	return OptEnvironmentMetadata{
		Value: v,
		Set:   true,
	}
}

// OptEnvironmentMetadata is optional EnvironmentMetadata.
type OptEnvironmentMetadata struct {
	Value EnvironmentMetadata
	Set   bool
}

// IsSet returns true if OptEnvironmentMetadata was set.
func (o OptEnvironmentMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEnvironmentMetadata) Reset() {
	var v EnvironmentMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEnvironmentMetadata) SetTo(v EnvironmentMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEnvironmentMetadata) Get() (v EnvironmentMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEnvironmentMetadata) Or(d EnvironmentMetadata) EnvironmentMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEnvironmentScope returns new OptEnvironmentScope with value set to v.
func NewOptEnvironmentScope(v EnvironmentScope) OptEnvironmentScope {
	return OptEnvironmentScope{
		Value: v,
		Set:   true,
	}
}

// OptEnvironmentScope is optional EnvironmentScope.
type OptEnvironmentScope struct {
	Value EnvironmentScope
	Set   bool
}

// IsSet returns true if OptEnvironmentScope was set.
func (o OptEnvironmentScope) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEnvironmentScope) Reset() {
	var v EnvironmentScope
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEnvironmentScope) SetTo(v EnvironmentScope) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEnvironmentScope) Get() (v EnvironmentScope, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEnvironmentScope) Or(d EnvironmentScope) EnvironmentScope {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNetworkingConfig returns new OptNetworkingConfig with value set to v.
func NewOptNetworkingConfig(v NetworkingConfig) OptNetworkingConfig {
	return OptNetworkingConfig{
		Value: v,
		Set:   true,
	}
}

// OptNetworkingConfig is optional NetworkingConfig.
type OptNetworkingConfig struct {
	Value NetworkingConfig
	Set   bool
}

// IsSet returns true if OptNetworkingConfig was set.
func (o OptNetworkingConfig) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNetworkingConfig) Reset() {
	var v NetworkingConfig
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptNetworkingConfig) SetTo(v NetworkingConfig) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNetworkingConfig) Get() (v NetworkingConfig, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNetworkingConfig) Or(d NetworkingConfig) NetworkingConfig {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPackagesConfig returns new OptPackagesConfig with value set to v.
func NewOptPackagesConfig(v PackagesConfig) OptPackagesConfig {
	return OptPackagesConfig{
		Value: v,
		Set:   true,
	}
}

// OptPackagesConfig is optional PackagesConfig.
type OptPackagesConfig struct {
	Value PackagesConfig
	Set   bool
}

// IsSet returns true if OptPackagesConfig was set.
func (o OptPackagesConfig) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPackagesConfig) Reset() {
	var v PackagesConfig
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPackagesConfig) SetTo(v PackagesConfig) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPackagesConfig) Get() (v PackagesConfig, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPackagesConfig) Or(d PackagesConfig) PackagesConfig {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPackagesConfigType returns new OptPackagesConfigType with value set to v.
func NewOptPackagesConfigType(v PackagesConfigType) OptPackagesConfigType {
	return OptPackagesConfigType{
		Value: v,
		Set:   true,
	}
}

// OptPackagesConfigType is optional PackagesConfigType.
type OptPackagesConfigType struct {
	Value PackagesConfigType
	Set   bool
}

// IsSet returns true if OptPackagesConfigType was set.
func (o OptPackagesConfigType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPackagesConfigType) Reset() {
	var v PackagesConfigType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPackagesConfigType) SetTo(v PackagesConfigType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPackagesConfigType) Get() (v PackagesConfigType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPackagesConfigType) Or(d PackagesConfigType) PackagesConfigType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptStopWorkBody returns new OptStopWorkBody with value set to v.
func NewOptStopWorkBody(v StopWorkBody) OptStopWorkBody {
	return OptStopWorkBody{
		Value: v,
		Set:   true,
	}
}

// OptStopWorkBody is optional StopWorkBody.
type OptStopWorkBody struct {
	Value StopWorkBody
	Set   bool
}

// IsSet returns true if OptStopWorkBody was set.
func (o OptStopWorkBody) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptStopWorkBody) Reset() {
	var v StopWorkBody
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptStopWorkBody) SetTo(v StopWorkBody) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptStopWorkBody) Get() (v StopWorkBody, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptStopWorkBody) Or(d StopWorkBody) StopWorkBody {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTosConfig returns new OptTosConfig with value set to v.
func NewOptTosConfig(v TosConfig) OptTosConfig {
	return OptTosConfig{
		Value: v,
		Set:   true,
	}
}

// OptTosConfig is optional TosConfig.
type OptTosConfig struct {
	Value TosConfig
	Set   bool
}

// IsSet returns true if OptTosConfig was set.
func (o OptTosConfig) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTosConfig) Reset() {
	var v TosConfig
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTosConfig) SetTo(v TosConfig) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTosConfig) Get() (v TosConfig, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTosConfig) Or(d TosConfig) TosConfig {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateEnvironmentRequestMetadata returns new OptUpdateEnvironmentRequestMetadata with value set to v.
func NewOptUpdateEnvironmentRequestMetadata(v UpdateEnvironmentRequestMetadata) OptUpdateEnvironmentRequestMetadata {
	return OptUpdateEnvironmentRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptUpdateEnvironmentRequestMetadata is optional UpdateEnvironmentRequestMetadata.
type OptUpdateEnvironmentRequestMetadata struct {
	Value UpdateEnvironmentRequestMetadata
	Set   bool
}

// IsSet returns true if OptUpdateEnvironmentRequestMetadata was set.
func (o OptUpdateEnvironmentRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateEnvironmentRequestMetadata) Reset() {
	var v UpdateEnvironmentRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateEnvironmentRequestMetadata) SetTo(v UpdateEnvironmentRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateEnvironmentRequestMetadata) Get() (v UpdateEnvironmentRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateEnvironmentRequestMetadata) Or(d UpdateEnvironmentRequestMetadata) UpdateEnvironmentRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// 启动时预装的依赖包。版本通过包管理器自身语义指定 (e.g. pip 用
// `"pkg==1.0.0"`；不指定版本则装最新)。.
// Ref: #/components/schemas/PackagesConfig
type PackagesConfig struct {
	// 固定 `"packages"`；标识这是 Packages 配置。.
	Type OptPackagesConfigType `json:"type"`
	// Pip 依赖条目列表。.
	Pip []string `json:"pip"`
	// Apt 包名列表。.
	Apt []string `json:"apt"`
	// Npm 包名列表。.
	Npm []string `json:"npm"`
	// Cargo crate 名列表。.
	Cargo []string `json:"cargo"`
	// RubyGems gem 名列表。.
	Gem []string `json:"gem"`
	// Go module import 路径列表。.
	Go []string `json:"go"`
}

// GetType returns the value of Type.
func (s *PackagesConfig) GetType() OptPackagesConfigType {
	return s.Type
}

// GetPip returns the value of Pip.
func (s *PackagesConfig) GetPip() []string {
	return s.Pip
}

// GetApt returns the value of Apt.
func (s *PackagesConfig) GetApt() []string {
	return s.Apt
}

// GetNpm returns the value of Npm.
func (s *PackagesConfig) GetNpm() []string {
	return s.Npm
}

// GetCargo returns the value of Cargo.
func (s *PackagesConfig) GetCargo() []string {
	return s.Cargo
}

// GetGem returns the value of Gem.
func (s *PackagesConfig) GetGem() []string {
	return s.Gem
}

// GetGo returns the value of Go.
func (s *PackagesConfig) GetGo() []string {
	return s.Go
}

// SetType sets the value of Type.
func (s *PackagesConfig) SetType(val OptPackagesConfigType) {
	s.Type = val
}

// SetPip sets the value of Pip.
func (s *PackagesConfig) SetPip(val []string) {
	s.Pip = val
}

// SetApt sets the value of Apt.
func (s *PackagesConfig) SetApt(val []string) {
	s.Apt = val
}

// SetNpm sets the value of Npm.
func (s *PackagesConfig) SetNpm(val []string) {
	s.Npm = val
}

// SetCargo sets the value of Cargo.
func (s *PackagesConfig) SetCargo(val []string) {
	s.Cargo = val
}

// SetGem sets the value of Gem.
func (s *PackagesConfig) SetGem(val []string) {
	s.Gem = val
}

// SetGo sets the value of Go.
func (s *PackagesConfig) SetGo(val []string) {
	s.Go = val
}

// 固定 `"packages"`；标识这是 Packages 配置。.
type PackagesConfigType string

const (
	PackagesConfigTypePackages PackagesConfigType = "packages"
)

// AllValues returns all PackagesConfigType values.
func (PackagesConfigType) AllValues() []PackagesConfigType {
	return []PackagesConfigType{
		PackagesConfigTypePackages,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PackagesConfigType) MarshalText() ([]byte, error) {
	switch s {
	case PackagesConfigTypePackages:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PackagesConfigType) UnmarshalText(data []byte) error {
	switch PackagesConfigType(data) {
	case PackagesConfigTypePackages:
		*s = PackagesConfigTypePackages
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Stop work 的请求体。.
// Ref: #/components/schemas/StopWorkBody
type StopWorkBody struct {
	// 是否强制停止。.
	Force OptBool `json:"force"`
}

// GetForce returns the value of Force.
func (s *StopWorkBody) GetForce() OptBool {
	return s.Force
}

// SetForce sets the value of Force.
func (s *StopWorkBody) SetForce(val OptBool) {
	s.Force = val
}

// Environment 产物存储位置。设置后 outputs 文件会注册到用户指定的 TOS
// bucket/prefix；不设置则走方舟默认存储。.
// Ref: #/components/schemas/TosConfig
type TosConfig struct {
	// TOS bucket 名称。.
	Bucket OptString `json:"bucket"`
	// TOS 前缀。.
	Prefix OptString `json:"prefix"`
}

// GetBucket returns the value of Bucket.
func (s *TosConfig) GetBucket() OptString {
	return s.Bucket
}

// GetPrefix returns the value of Prefix.
func (s *TosConfig) GetPrefix() OptString {
	return s.Prefix
}

// SetBucket sets the value of Bucket.
func (s *TosConfig) SetBucket(val OptString) {
	s.Bucket = val
}

// SetPrefix sets the value of Prefix.
func (s *TosConfig) SetPrefix(val OptString) {
	s.Prefix = val
}

// 更新 Environment 的请求体。语义：
// - 省略字段 = 保留原值
// - `description` 显式空字符串或 null = 清空
// - `config` 嵌套字段按 patch 处理
// - `metadata` 走 patch.
// Ref: #/components/schemas/UpdateEnvironmentRequest
type UpdateEnvironmentRequest struct {
	// 人类可读名称。.
	Name OptString `json:"name"`
	// 运行环境配置。.
	Config OptEnvConfig `json:"config"`
	// 描述信息。.
	Description OptString `json:"description"`
	// 用户自定义键值对元数据。.
	Metadata OptUpdateEnvironmentRequestMetadata `json:"metadata"`
	// 一期未启用；仅协议占位。.
	Scope OptEnvironmentScope `json:"scope"`
}

// GetName returns the value of Name.
func (s *UpdateEnvironmentRequest) GetName() OptString {
	return s.Name
}

// GetConfig returns the value of Config.
func (s *UpdateEnvironmentRequest) GetConfig() OptEnvConfig {
	return s.Config
}

// GetDescription returns the value of Description.
func (s *UpdateEnvironmentRequest) GetDescription() OptString {
	return s.Description
}

// GetMetadata returns the value of Metadata.
func (s *UpdateEnvironmentRequest) GetMetadata() OptUpdateEnvironmentRequestMetadata {
	return s.Metadata
}

// GetScope returns the value of Scope.
func (s *UpdateEnvironmentRequest) GetScope() OptEnvironmentScope {
	return s.Scope
}

// SetName sets the value of Name.
func (s *UpdateEnvironmentRequest) SetName(val OptString) {
	s.Name = val
}

// SetConfig sets the value of Config.
func (s *UpdateEnvironmentRequest) SetConfig(val OptEnvConfig) {
	s.Config = val
}

// SetDescription sets the value of Description.
func (s *UpdateEnvironmentRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetMetadata sets the value of Metadata.
func (s *UpdateEnvironmentRequest) SetMetadata(val OptUpdateEnvironmentRequestMetadata) {
	s.Metadata = val
}

// SetScope sets the value of Scope.
func (s *UpdateEnvironmentRequest) SetScope(val OptEnvironmentScope) {
	s.Scope = val
}

// 用户自定义键值对元数据。.
type UpdateEnvironmentRequestMetadata map[string]string

func (s *UpdateEnvironmentRequestMetadata) init() UpdateEnvironmentRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Work 关联的标签。.
// Ref: #/components/schemas/VolcTag
type VolcTag struct {
	// 标签 key。.
	Key string `json:"key"`
	// 标签 value。.
	Value OptString `json:"value"`
}

// GetKey returns the value of Key.
func (s *VolcTag) GetKey() string {
	return s.Key
}

// GetValue returns the value of Value.
func (s *VolcTag) GetValue() OptString {
	return s.Value
}

// SetKey sets the value of Key.
func (s *VolcTag) SetKey(val string) {
	s.Key = val
}

// SetValue sets the value of Value.
func (s *VolcTag) SetValue(val OptString) {
	s.Value = val
}

// Work 的业务载荷。.
// Ref: #/components/schemas/WorkData
type WorkData struct {
	// 业务对象 ID，例如 session ID。.
	ID string `json:"id"`
	// 业务载荷类型，例如 `session`。.
	Type string `json:"type"`
}

// GetID returns the value of ID.
func (s *WorkData) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *WorkData) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *WorkData) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *WorkData) SetType(val string) {
	s.Type = val
}

// Worker queue 中的一条 work。.
// Ref: #/components/schemas/WorkItem
type WorkItem struct {
	// Work ID。.
	ID string `json:"id"`
	// Work ack 时间，RFC 3339。.
	AcknowledgedAt OptString `json:"acknowledged_at"`
	// Work 创建时间，RFC 3339。.
	CreatedAt string `json:"created_at"`
	// 业务载荷。.
	Data WorkData `json:"data"`
	// Environment ID。.
	EnvironmentID string `json:"environment_id"`
	// 最近 heartbeat 时间，RFC 3339。.
	LatestHeartbeatAt OptString `json:"latest_heartbeat_at"`
	// Work 标签。.
	Tags []VolcTag `json:"tags"`
	// Work secret；仅 poll 时返回，ack / stop 响应会抹掉。.
	Secret OptString `json:"secret"`
	// Work 开始时间，RFC 3339。.
	StartedAt OptString `json:"started_at"`
	// Work 生命周期状态。.
	State WorkState `json:"state"`
	// 控制面请求停止的时间，RFC 3339。.
	StopRequestedAt OptString `json:"stop_requested_at"`
	// Work 停止时间，RFC 3339。.
	StoppedAt OptString `json:"stopped_at"`
	// 对象类型，固定为 `work`。.
	Type WorkItemType `json:"type"`
}

// GetID returns the value of ID.
func (s *WorkItem) GetID() string {
	return s.ID
}

// GetAcknowledgedAt returns the value of AcknowledgedAt.
func (s *WorkItem) GetAcknowledgedAt() OptString {
	return s.AcknowledgedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *WorkItem) GetCreatedAt() string {
	return s.CreatedAt
}

// GetData returns the value of Data.
func (s *WorkItem) GetData() WorkData {
	return s.Data
}

// GetEnvironmentID returns the value of EnvironmentID.
func (s *WorkItem) GetEnvironmentID() string {
	return s.EnvironmentID
}

// GetLatestHeartbeatAt returns the value of LatestHeartbeatAt.
func (s *WorkItem) GetLatestHeartbeatAt() OptString {
	return s.LatestHeartbeatAt
}

// GetTags returns the value of Tags.
func (s *WorkItem) GetTags() []VolcTag {
	return s.Tags
}

// GetSecret returns the value of Secret.
func (s *WorkItem) GetSecret() OptString {
	return s.Secret
}

// GetStartedAt returns the value of StartedAt.
func (s *WorkItem) GetStartedAt() OptString {
	return s.StartedAt
}

// GetState returns the value of State.
func (s *WorkItem) GetState() WorkState {
	return s.State
}

// GetStopRequestedAt returns the value of StopRequestedAt.
func (s *WorkItem) GetStopRequestedAt() OptString {
	return s.StopRequestedAt
}

// GetStoppedAt returns the value of StoppedAt.
func (s *WorkItem) GetStoppedAt() OptString {
	return s.StoppedAt
}

// GetType returns the value of Type.
func (s *WorkItem) GetType() WorkItemType {
	return s.Type
}

// SetID sets the value of ID.
func (s *WorkItem) SetID(val string) {
	s.ID = val
}

// SetAcknowledgedAt sets the value of AcknowledgedAt.
func (s *WorkItem) SetAcknowledgedAt(val OptString) {
	s.AcknowledgedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *WorkItem) SetCreatedAt(val string) {
	s.CreatedAt = val
}

// SetData sets the value of Data.
func (s *WorkItem) SetData(val WorkData) {
	s.Data = val
}

// SetEnvironmentID sets the value of EnvironmentID.
func (s *WorkItem) SetEnvironmentID(val string) {
	s.EnvironmentID = val
}

// SetLatestHeartbeatAt sets the value of LatestHeartbeatAt.
func (s *WorkItem) SetLatestHeartbeatAt(val OptString) {
	s.LatestHeartbeatAt = val
}

// SetTags sets the value of Tags.
func (s *WorkItem) SetTags(val []VolcTag) {
	s.Tags = val
}

// SetSecret sets the value of Secret.
func (s *WorkItem) SetSecret(val OptString) {
	s.Secret = val
}

// SetStartedAt sets the value of StartedAt.
func (s *WorkItem) SetStartedAt(val OptString) {
	s.StartedAt = val
}

// SetState sets the value of State.
func (s *WorkItem) SetState(val WorkState) {
	s.State = val
}

// SetStopRequestedAt sets the value of StopRequestedAt.
func (s *WorkItem) SetStopRequestedAt(val OptString) {
	s.StopRequestedAt = val
}

// SetStoppedAt sets the value of StoppedAt.
func (s *WorkItem) SetStoppedAt(val OptString) {
	s.StoppedAt = val
}

// SetType sets the value of Type.
func (s *WorkItem) SetType(val WorkItemType) {
	s.Type = val
}

// 对象类型，固定为 `work`。.
type WorkItemType string

const (
	WorkItemTypeWork WorkItemType = "work"
)

// AllValues returns all WorkItemType values.
func (WorkItemType) AllValues() []WorkItemType {
	return []WorkItemType{
		WorkItemTypeWork,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WorkItemType) MarshalText() ([]byte, error) {
	switch s {
	case WorkItemTypeWork:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WorkItemType) UnmarshalText(data []byte) error {
	switch WorkItemType(data) {
	case WorkItemTypeWork:
		*s = WorkItemTypeWork
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Work 生命周期状态。.
// Ref: #/components/schemas/WorkState
type WorkState string

const (
	WorkStateQueued   WorkState = "queued"
	WorkStateStarting WorkState = "starting"
	WorkStateActive   WorkState = "active"
	WorkStateStopping WorkState = "stopping"
	WorkStateStopped  WorkState = "stopped"
)

// AllValues returns all WorkState values.
func (WorkState) AllValues() []WorkState {
	return []WorkState{
		WorkStateQueued,
		WorkStateStarting,
		WorkStateActive,
		WorkStateStopping,
		WorkStateStopped,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WorkState) MarshalText() ([]byte, error) {
	switch s {
	case WorkStateQueued:
		return []byte(s), nil
	case WorkStateStarting:
		return []byte(s), nil
	case WorkStateActive:
		return []byte(s), nil
	case WorkStateStopping:
		return []byte(s), nil
	case WorkStateStopped:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WorkState) UnmarshalText(data []byte) error {
	switch WorkState(data) {
	case WorkStateQueued:
		*s = WorkStateQueued
		return nil
	case WorkStateStarting:
		*s = WorkStateStarting
		return nil
	case WorkStateActive:
		*s = WorkStateActive
		return nil
	case WorkStateStopping:
		*s = WorkStateStopping
		return nil
	case WorkStateStopped:
		*s = WorkStateStopped
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
