run:
  timeout: 5m

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 3
  goimports:
    local-prefixes: github.com/volcengine/ark-runtime-go
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  enable:
    - revive
    - goconst
    - gofmt
    - goimports
    - misspell
    - govet

issues:
  exclude-dirs:
    - examples
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - revive
    - path: oas_.*_gen\.go
      linters:
        - revive
        - goconst
        - misspell
