// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package tokenization

import (
	"github.com/go-faster/errors"
)

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Input text(s) to tokenize. A single string tokenizes one input; an array
// of strings tokenizes each element independently.
// Ref: #/components/schemas/TokenizationInput
// TokenizationInput represents sum type.
type TokenizationInput struct {
	Type        TokenizationInputType // switch on this field
	String      string
	StringArray []string
}

// TokenizationInputType is oneOf type of TokenizationInput.
type TokenizationInputType string

// Possible values for TokenizationInputType.
const (
	StringTokenizationInput      TokenizationInputType = "string"
	StringArrayTokenizationInput TokenizationInputType = "[]string"
)

// IsString reports whether TokenizationInput is string.
func (s TokenizationInput) IsString() bool { return s.Type == StringTokenizationInput }

// IsStringArray reports whether TokenizationInput is []string.
func (s TokenizationInput) IsStringArray() bool { return s.Type == StringArrayTokenizationInput }

// SetString sets TokenizationInput to string.
func (s *TokenizationInput) SetString(v string) {
	s.Type = StringTokenizationInput
	s.String = v
}

// GetString returns string and true boolean if TokenizationInput is string.
func (s TokenizationInput) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringTokenizationInput returns new TokenizationInput from string.
func NewStringTokenizationInput(v string) TokenizationInput {
	var s TokenizationInput
	s.SetString(v)
	return s
}

// SetStringArray sets TokenizationInput to []string.
func (s *TokenizationInput) SetStringArray(v []string) {
	s.Type = StringArrayTokenizationInput
	s.StringArray = v
}

// GetStringArray returns []string and true boolean if TokenizationInput is []string.
func (s TokenizationInput) GetStringArray() (v []string, ok bool) {
	if !s.IsStringArray() {
		return v, false
	}
	return s.StringArray, true
}

// NewStringArrayTokenizationInput returns new TokenizationInput from []string.
func NewStringArrayTokenizationInput(v []string) TokenizationInput {
	var s TokenizationInput
	s.SetStringArray(v)
	return s
}

// A single tokenization result for one input string.
// Ref: #/components/schemas/TokenizationItem
type TokenizationItem struct {
	// The index of this result in the request `text` array.
	Index int32 `json:"index"`
	// The object type. Always `tokenization`.
	Object TokenizationItemObject `json:"object"`
	// The total number of tokens produced for this input.
	TotalTokens int64 `json:"total_tokens"`
	// The token IDs produced by the tokenizer, in order.
	TokenIds []int64 `json:"token_ids"`
	// Per-token character offsets into the input string, as
	// `[start, end]` pairs aligned with `token_ids`.
	OffsetMapping [][]int64 `json:"offset_mapping"`
}

// GetIndex returns the value of Index.
func (s *TokenizationItem) GetIndex() int32 {
	return s.Index
}

// GetObject returns the value of Object.
func (s *TokenizationItem) GetObject() TokenizationItemObject {
	return s.Object
}

// GetTotalTokens returns the value of TotalTokens.
func (s *TokenizationItem) GetTotalTokens() int64 {
	return s.TotalTokens
}

// GetTokenIds returns the value of TokenIds.
func (s *TokenizationItem) GetTokenIds() []int64 {
	return s.TokenIds
}

// GetOffsetMapping returns the value of OffsetMapping.
func (s *TokenizationItem) GetOffsetMapping() [][]int64 {
	return s.OffsetMapping
}

// SetIndex sets the value of Index.
func (s *TokenizationItem) SetIndex(val int32) {
	s.Index = val
}

// SetObject sets the value of Object.
func (s *TokenizationItem) SetObject(val TokenizationItemObject) {
	s.Object = val
}

// SetTotalTokens sets the value of TotalTokens.
func (s *TokenizationItem) SetTotalTokens(val int64) {
	s.TotalTokens = val
}

// SetTokenIds sets the value of TokenIds.
func (s *TokenizationItem) SetTokenIds(val []int64) {
	s.TokenIds = val
}

// SetOffsetMapping sets the value of OffsetMapping.
func (s *TokenizationItem) SetOffsetMapping(val [][]int64) {
	s.OffsetMapping = val
}

// The object type. Always `tokenization`.
type TokenizationItemObject string

const (
	TokenizationItemObjectTokenization TokenizationItemObject = "tokenization"
)

// AllValues returns all TokenizationItemObject values.
func (TokenizationItemObject) AllValues() []TokenizationItemObject {
	return []TokenizationItemObject{
		TokenizationItemObjectTokenization,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TokenizationItemObject) MarshalText() ([]byte, error) {
	switch s {
	case TokenizationItemObjectTokenization:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TokenizationItemObject) UnmarshalText(data []byte) error {
	switch TokenizationItemObject(data) {
	case TokenizationItemObjectTokenization:
		*s = TokenizationItemObjectTokenization
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/TokenizationRequest
type TokenizationRequest struct {
	// Endpoint ID or model name to tokenize for.
	Model string `json:"model"`
	// Input text to tokenize, as a string or array of strings. To tokenize
	// multiple inputs in one request, pass an array.
	Text TokenizationInput `json:"text"`
	// A unique identifier representing the end-user. Currently accepted but
	// not used by the server; reserved for parity with other endpoints.
	User OptString `json:"user"`
}

// GetModel returns the value of Model.
func (s *TokenizationRequest) GetModel() string {
	return s.Model
}

// GetText returns the value of Text.
func (s *TokenizationRequest) GetText() TokenizationInput {
	return s.Text
}

// GetUser returns the value of User.
func (s *TokenizationRequest) GetUser() OptString {
	return s.User
}

// SetModel sets the value of Model.
func (s *TokenizationRequest) SetModel(val string) {
	s.Model = val
}

// SetText sets the value of Text.
func (s *TokenizationRequest) SetText(val TokenizationInput) {
	s.Text = val
}

// SetUser sets the value of User.
func (s *TokenizationRequest) SetUser(val OptString) {
	s.User = val
}

// Ref: #/components/schemas/TokenizationResponse
type TokenizationResponse struct {
	// A unique identifier for the tokenization response.
	ID string `json:"id"`
	// The object type. Always `list`.
	Object TokenizationResponseObject `json:"object"`
	// Unix timestamp (in seconds) of when the response was created.
	Created int64 `json:"created"`
	// The model that produced the tokenization.
	Model string `json:"model"`
	// The list of tokenization results, one per input.
	Data []TokenizationItem `json:"data"`
}

// GetID returns the value of ID.
func (s *TokenizationResponse) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *TokenizationResponse) GetObject() TokenizationResponseObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *TokenizationResponse) GetCreated() int64 {
	return s.Created
}

// GetModel returns the value of Model.
func (s *TokenizationResponse) GetModel() string {
	return s.Model
}

// GetData returns the value of Data.
func (s *TokenizationResponse) GetData() []TokenizationItem {
	return s.Data
}

// SetID sets the value of ID.
func (s *TokenizationResponse) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *TokenizationResponse) SetObject(val TokenizationResponseObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *TokenizationResponse) SetCreated(val int64) {
	s.Created = val
}

// SetModel sets the value of Model.
func (s *TokenizationResponse) SetModel(val string) {
	s.Model = val
}

// SetData sets the value of Data.
func (s *TokenizationResponse) SetData(val []TokenizationItem) {
	s.Data = val
}

// The object type. Always `list`.
type TokenizationResponseObject string

const (
	TokenizationResponseObjectList TokenizationResponseObject = "list"
)

// AllValues returns all TokenizationResponseObject values.
func (TokenizationResponseObject) AllValues() []TokenizationResponseObject {
	return []TokenizationResponseObject{
		TokenizationResponseObjectList,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TokenizationResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case TokenizationResponseObjectList:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TokenizationResponseObject) UnmarshalText(data []byte) error {
	switch TokenizationResponseObject(data) {
	case TokenizationResponseObjectList:
		*s = TokenizationResponseObjectList
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
