// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package multimodalembedding

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/Embedding
// Embedding represents sum type.
type Embedding struct {
	Type         EmbeddingType // switch on this field
	Float64Array []float64
	String       string
}

// EmbeddingType is oneOf type of Embedding.
type EmbeddingType string

// Possible values for EmbeddingType.
const (
	Float64ArrayEmbedding EmbeddingType = "[]float64"
	StringEmbedding       EmbeddingType = "string"
)

// IsFloat64Array reports whether Embedding is []float64.
func (s Embedding) IsFloat64Array() bool { return s.Type == Float64ArrayEmbedding }

// IsString reports whether Embedding is string.
func (s Embedding) IsString() bool { return s.Type == StringEmbedding }

// SetFloat64Array sets Embedding to []float64.
func (s *Embedding) SetFloat64Array(v []float64) {
	s.Type = Float64ArrayEmbedding
	s.Float64Array = v
}

// GetFloat64Array returns []float64 and true boolean if Embedding is []float64.
func (s Embedding) GetFloat64Array() (v []float64, ok bool) {
	if !s.IsFloat64Array() {
		return v, false
	}
	return s.Float64Array, true
}

// NewFloat64ArrayEmbedding returns new Embedding from []float64.
func NewFloat64ArrayEmbedding(v []float64) Embedding {
	var s Embedding
	s.SetFloat64Array(v)
	return s
}

// SetString sets Embedding to string.
func (s *Embedding) SetString(v string) {
	s.Type = StringEmbedding
	s.String = v
}

// GetString returns string and true boolean if Embedding is string.
func (s Embedding) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringEmbedding returns new Embedding from string.
func NewStringEmbedding(v string) Embedding {
	var s Embedding
	s.SetString(v)
	return s
}

// Ref: #/components/schemas/EmbeddingDataItem
type EmbeddingDataItem struct {
	// The (dense) embedding vector.
	Embedding Embedding `json:"embedding"`
	// Sparse embedding entries when sparse embeddings were requested.
	SparseEmbedding []SparseEmbeddingValue `json:"sparse_embedding"`
	// The object type. Always `embedding`.
	Object EmbeddingDataItemObject `json:"object"`
	// Per-modality embeddings when `multi_embedding` was requested.
	MultiEmbedding []Embedding `json:"multi_embedding"`
}

// GetEmbedding returns the value of Embedding.
func (s *EmbeddingDataItem) GetEmbedding() Embedding {
	return s.Embedding
}

// GetSparseEmbedding returns the value of SparseEmbedding.
func (s *EmbeddingDataItem) GetSparseEmbedding() []SparseEmbeddingValue {
	return s.SparseEmbedding
}

// GetObject returns the value of Object.
func (s *EmbeddingDataItem) GetObject() EmbeddingDataItemObject {
	return s.Object
}

// GetMultiEmbedding returns the value of MultiEmbedding.
func (s *EmbeddingDataItem) GetMultiEmbedding() []Embedding {
	return s.MultiEmbedding
}

// SetEmbedding sets the value of Embedding.
func (s *EmbeddingDataItem) SetEmbedding(val Embedding) {
	s.Embedding = val
}

// SetSparseEmbedding sets the value of SparseEmbedding.
func (s *EmbeddingDataItem) SetSparseEmbedding(val []SparseEmbeddingValue) {
	s.SparseEmbedding = val
}

// SetObject sets the value of Object.
func (s *EmbeddingDataItem) SetObject(val EmbeddingDataItemObject) {
	s.Object = val
}

// SetMultiEmbedding sets the value of MultiEmbedding.
func (s *EmbeddingDataItem) SetMultiEmbedding(val []Embedding) {
	s.MultiEmbedding = val
}

// The object type. Always `embedding`.
type EmbeddingDataItemObject string

const (
	EmbeddingDataItemObjectEmbedding EmbeddingDataItemObject = "embedding"
)

// AllValues returns all EmbeddingDataItemObject values.
func (EmbeddingDataItemObject) AllValues() []EmbeddingDataItemObject {
	return []EmbeddingDataItemObject{
		EmbeddingDataItemObjectEmbedding,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EmbeddingDataItemObject) MarshalText() ([]byte, error) {
	switch s {
	case EmbeddingDataItemObjectEmbedding:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EmbeddingDataItemObject) UnmarshalText(data []byte) error {
	switch EmbeddingDataItemObject(data) {
	case EmbeddingDataItemObjectEmbedding:
		*s = EmbeddingDataItemObjectEmbedding
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/EmbeddingInput
type EmbeddingInput struct {
	// Discriminator for which content field is set.
	Type EmbeddingInputType `json:"type"`
	// Text content. Required when `type` is `text`.
	Text OptString `json:"text"`
	// Image content. Required when `type` is `image_url`.
	ImageURL OptImageURL `json:"image_url"`
	// Video content. Required when `type` is `video_url`.
	VideoURL OptVideoURL `json:"video_url"`
}

// GetType returns the value of Type.
func (s *EmbeddingInput) GetType() EmbeddingInputType {
	return s.Type
}

// GetText returns the value of Text.
func (s *EmbeddingInput) GetText() OptString {
	return s.Text
}

// GetImageURL returns the value of ImageURL.
func (s *EmbeddingInput) GetImageURL() OptImageURL {
	return s.ImageURL
}

// GetVideoURL returns the value of VideoURL.
func (s *EmbeddingInput) GetVideoURL() OptVideoURL {
	return s.VideoURL
}

// SetType sets the value of Type.
func (s *EmbeddingInput) SetType(val EmbeddingInputType) {
	s.Type = val
}

// SetText sets the value of Text.
func (s *EmbeddingInput) SetText(val OptString) {
	s.Text = val
}

// SetImageURL sets the value of ImageURL.
func (s *EmbeddingInput) SetImageURL(val OptImageURL) {
	s.ImageURL = val
}

// SetVideoURL sets the value of VideoURL.
func (s *EmbeddingInput) SetVideoURL(val OptVideoURL) {
	s.VideoURL = val
}

// Ref: #/components/schemas/EmbeddingInputType
type EmbeddingInputType string

const (
	EmbeddingInputTypeText     EmbeddingInputType = "text"
	EmbeddingInputTypeImageURL EmbeddingInputType = "image_url"
	EmbeddingInputTypeVideoURL EmbeddingInputType = "video_url"
)

// AllValues returns all EmbeddingInputType values.
func (EmbeddingInputType) AllValues() []EmbeddingInputType {
	return []EmbeddingInputType{
		EmbeddingInputTypeText,
		EmbeddingInputTypeImageURL,
		EmbeddingInputTypeVideoURL,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EmbeddingInputType) MarshalText() ([]byte, error) {
	switch s {
	case EmbeddingInputTypeText:
		return []byte(s), nil
	case EmbeddingInputTypeImageURL:
		return []byte(s), nil
	case EmbeddingInputTypeVideoURL:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EmbeddingInputType) UnmarshalText(data []byte) error {
	switch EmbeddingInputType(data) {
	case EmbeddingInputTypeText:
		*s = EmbeddingInputTypeText
		return nil
	case EmbeddingInputTypeImageURL:
		*s = EmbeddingInputTypeImageURL
		return nil
	case EmbeddingInputTypeVideoURL:
		*s = EmbeddingInputTypeVideoURL
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/EmbeddingUsage
type EmbeddingUsage struct {
	// The number of prompt tokens used.
	PromptTokens int64 `json:"prompt_tokens"`
	// The total number of tokens used.
	TotalTokens int64 `json:"total_tokens"`
	// A detailed breakdown of the prompt tokens.
	PromptTokensDetails PromptTokensDetails `json:"prompt_tokens_details"`
}

// GetPromptTokens returns the value of PromptTokens.
func (s *EmbeddingUsage) GetPromptTokens() int64 {
	return s.PromptTokens
}

// GetTotalTokens returns the value of TotalTokens.
func (s *EmbeddingUsage) GetTotalTokens() int64 {
	return s.TotalTokens
}

// GetPromptTokensDetails returns the value of PromptTokensDetails.
func (s *EmbeddingUsage) GetPromptTokensDetails() PromptTokensDetails {
	return s.PromptTokensDetails
}

// SetPromptTokens sets the value of PromptTokens.
func (s *EmbeddingUsage) SetPromptTokens(val int64) {
	s.PromptTokens = val
}

// SetTotalTokens sets the value of TotalTokens.
func (s *EmbeddingUsage) SetTotalTokens(val int64) {
	s.TotalTokens = val
}

// SetPromptTokensDetails sets the value of PromptTokensDetails.
func (s *EmbeddingUsage) SetPromptTokensDetails(val PromptTokensDetails) {
	s.PromptTokensDetails = val
}

// Ref: #/components/schemas/EncodingFormat
type EncodingFormat string

const (
	EncodingFormatBase64 EncodingFormat = "base64"
	EncodingFormatFloat  EncodingFormat = "float"
)

// AllValues returns all EncodingFormat values.
func (EncodingFormat) AllValues() []EncodingFormat {
	return []EncodingFormat{
		EncodingFormatBase64,
		EncodingFormatFloat,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EncodingFormat) MarshalText() ([]byte, error) {
	switch s {
	case EncodingFormatBase64:
		return []byte(s), nil
	case EncodingFormatFloat:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EncodingFormat) UnmarshalText(data []byte) error {
	switch EncodingFormat(data) {
	case EncodingFormatBase64:
		*s = EncodingFormatBase64
		return nil
	case EncodingFormatFloat:
		*s = EncodingFormatFloat
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ImageURL
type ImageURL struct {
	// The URL of the image to embed.
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *ImageURL) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *ImageURL) SetURL(val string) {
	s.URL = val
}

// Ref: #/components/schemas/MultiEmbeddingConfig
type MultiEmbeddingConfig struct {
	// Whether per-modality embeddings should be returned in addition to the joint embedding.
	Type MultiEmbeddingMode `json:"type"`
}

// GetType returns the value of Type.
func (s *MultiEmbeddingConfig) GetType() MultiEmbeddingMode {
	return s.Type
}

// SetType sets the value of Type.
func (s *MultiEmbeddingConfig) SetType(val MultiEmbeddingMode) {
	s.Type = val
}

// Ref: #/components/schemas/MultiEmbeddingMode
type MultiEmbeddingMode string

const (
	MultiEmbeddingModeEnabled  MultiEmbeddingMode = "enabled"
	MultiEmbeddingModeDisabled MultiEmbeddingMode = "disabled"
)

// AllValues returns all MultiEmbeddingMode values.
func (MultiEmbeddingMode) AllValues() []MultiEmbeddingMode {
	return []MultiEmbeddingMode{
		MultiEmbeddingModeEnabled,
		MultiEmbeddingModeDisabled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MultiEmbeddingMode) MarshalText() ([]byte, error) {
	switch s {
	case MultiEmbeddingModeEnabled:
		return []byte(s), nil
	case MultiEmbeddingModeDisabled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MultiEmbeddingMode) UnmarshalText(data []byte) error {
	switch MultiEmbeddingMode(data) {
	case MultiEmbeddingModeEnabled:
		*s = MultiEmbeddingModeEnabled
		return nil
	case MultiEmbeddingModeDisabled:
		*s = MultiEmbeddingModeDisabled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/MultiModalEmbeddingRequest
type MultiModalEmbeddingRequest struct {
	// The model identifier to use.
	Model string `json:"model"`
	// The list of multimodal inputs to embed.
	Input []EmbeddingInput `json:"input"`
	// The format embeddings are returned in. Defaults to `float`.
	EncodingFormat OptEncodingFormat `json:"encoding_format"`
	// Override the embedding dimensionality.
	Dimensions OptInt64 `json:"dimensions"`
	// Sparse embedding configuration.
	SparseEmbedding OptSparseEmbeddingConfig `json:"sparse_embedding"`
	// Multi-embedding configuration (per-modality vectors).
	MultiEmbedding OptMultiEmbeddingConfig `json:"multi_embedding"`
	// Optional natural-language instructions to steer the embedding.
	Instructions OptString `json:"instructions"`
}

// GetModel returns the value of Model.
func (s *MultiModalEmbeddingRequest) GetModel() string {
	return s.Model
}

// GetInput returns the value of Input.
func (s *MultiModalEmbeddingRequest) GetInput() []EmbeddingInput {
	return s.Input
}

// GetEncodingFormat returns the value of EncodingFormat.
func (s *MultiModalEmbeddingRequest) GetEncodingFormat() OptEncodingFormat {
	return s.EncodingFormat
}

// GetDimensions returns the value of Dimensions.
func (s *MultiModalEmbeddingRequest) GetDimensions() OptInt64 {
	return s.Dimensions
}

// GetSparseEmbedding returns the value of SparseEmbedding.
func (s *MultiModalEmbeddingRequest) GetSparseEmbedding() OptSparseEmbeddingConfig {
	return s.SparseEmbedding
}

// GetMultiEmbedding returns the value of MultiEmbedding.
func (s *MultiModalEmbeddingRequest) GetMultiEmbedding() OptMultiEmbeddingConfig {
	return s.MultiEmbedding
}

// GetInstructions returns the value of Instructions.
func (s *MultiModalEmbeddingRequest) GetInstructions() OptString {
	return s.Instructions
}

// SetModel sets the value of Model.
func (s *MultiModalEmbeddingRequest) SetModel(val string) {
	s.Model = val
}

// SetInput sets the value of Input.
func (s *MultiModalEmbeddingRequest) SetInput(val []EmbeddingInput) {
	s.Input = val
}

// SetEncodingFormat sets the value of EncodingFormat.
func (s *MultiModalEmbeddingRequest) SetEncodingFormat(val OptEncodingFormat) {
	s.EncodingFormat = val
}

// SetDimensions sets the value of Dimensions.
func (s *MultiModalEmbeddingRequest) SetDimensions(val OptInt64) {
	s.Dimensions = val
}

// SetSparseEmbedding sets the value of SparseEmbedding.
func (s *MultiModalEmbeddingRequest) SetSparseEmbedding(val OptSparseEmbeddingConfig) {
	s.SparseEmbedding = val
}

// SetMultiEmbedding sets the value of MultiEmbedding.
func (s *MultiModalEmbeddingRequest) SetMultiEmbedding(val OptMultiEmbeddingConfig) {
	s.MultiEmbedding = val
}

// SetInstructions sets the value of Instructions.
func (s *MultiModalEmbeddingRequest) SetInstructions(val OptString) {
	s.Instructions = val
}

// Ref: #/components/schemas/MultiModalEmbeddingResponse
type MultiModalEmbeddingResponse struct {
	// The unique identifier for the embedding response.
	ID string `json:"id"`
	// The model that produced the embeddings.
	Model string `json:"model"`
	// Unix timestamp (in seconds) of when the response was created.
	Created int64 `json:"created"`
	// The object type. Always `list`.
	Object MultiModalEmbeddingResponseObject `json:"object"`
	// The embedding result.
	Data EmbeddingDataItem `json:"data"`
	// Token usage information.
	Usage EmbeddingUsage `json:"usage"`
}

// GetID returns the value of ID.
func (s *MultiModalEmbeddingResponse) GetID() string {
	return s.ID
}

// GetModel returns the value of Model.
func (s *MultiModalEmbeddingResponse) GetModel() string {
	return s.Model
}

// GetCreated returns the value of Created.
func (s *MultiModalEmbeddingResponse) GetCreated() int64 {
	return s.Created
}

// GetObject returns the value of Object.
func (s *MultiModalEmbeddingResponse) GetObject() MultiModalEmbeddingResponseObject {
	return s.Object
}

// GetData returns the value of Data.
func (s *MultiModalEmbeddingResponse) GetData() EmbeddingDataItem {
	return s.Data
}

// GetUsage returns the value of Usage.
func (s *MultiModalEmbeddingResponse) GetUsage() EmbeddingUsage {
	return s.Usage
}

// SetID sets the value of ID.
func (s *MultiModalEmbeddingResponse) SetID(val string) {
	s.ID = val
}

// SetModel sets the value of Model.
func (s *MultiModalEmbeddingResponse) SetModel(val string) {
	s.Model = val
}

// SetCreated sets the value of Created.
func (s *MultiModalEmbeddingResponse) SetCreated(val int64) {
	s.Created = val
}

// SetObject sets the value of Object.
func (s *MultiModalEmbeddingResponse) SetObject(val MultiModalEmbeddingResponseObject) {
	s.Object = val
}

// SetData sets the value of Data.
func (s *MultiModalEmbeddingResponse) SetData(val EmbeddingDataItem) {
	s.Data = val
}

// SetUsage sets the value of Usage.
func (s *MultiModalEmbeddingResponse) SetUsage(val EmbeddingUsage) {
	s.Usage = val
}

// The object type. Always `list`.
type MultiModalEmbeddingResponseObject string

const (
	MultiModalEmbeddingResponseObjectList MultiModalEmbeddingResponseObject = "list"
)

// AllValues returns all MultiModalEmbeddingResponseObject values.
func (MultiModalEmbeddingResponseObject) AllValues() []MultiModalEmbeddingResponseObject {
	return []MultiModalEmbeddingResponseObject{
		MultiModalEmbeddingResponseObjectList,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MultiModalEmbeddingResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case MultiModalEmbeddingResponseObjectList:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MultiModalEmbeddingResponseObject) UnmarshalText(data []byte) error {
	switch MultiModalEmbeddingResponseObject(data) {
	case MultiModalEmbeddingResponseObjectList:
		*s = MultiModalEmbeddingResponseObjectList
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptEncodingFormat returns new OptEncodingFormat with value set to v.
func NewOptEncodingFormat(v EncodingFormat) OptEncodingFormat {
	return OptEncodingFormat{
		Value: v,
		Set:   true,
	}
}

// OptEncodingFormat is optional EncodingFormat.
type OptEncodingFormat struct {
	Value EncodingFormat
	Set   bool
}

// IsSet returns true if OptEncodingFormat was set.
func (o OptEncodingFormat) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEncodingFormat) Reset() {
	var v EncodingFormat
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEncodingFormat) SetTo(v EncodingFormat) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEncodingFormat) Get() (v EncodingFormat, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEncodingFormat) Or(d EncodingFormat) EncodingFormat {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptImageURL returns new OptImageURL with value set to v.
func NewOptImageURL(v ImageURL) OptImageURL {
	return OptImageURL{
		Value: v,
		Set:   true,
	}
}

// OptImageURL is optional ImageURL.
type OptImageURL struct {
	Value ImageURL
	Set   bool
}

// IsSet returns true if OptImageURL was set.
func (o OptImageURL) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptImageURL) Reset() {
	var v ImageURL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptImageURL) SetTo(v ImageURL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptImageURL) Get() (v ImageURL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptImageURL) Or(d ImageURL) ImageURL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMultiEmbeddingConfig returns new OptMultiEmbeddingConfig with value set to v.
func NewOptMultiEmbeddingConfig(v MultiEmbeddingConfig) OptMultiEmbeddingConfig {
	return OptMultiEmbeddingConfig{
		Value: v,
		Set:   true,
	}
}

// OptMultiEmbeddingConfig is optional MultiEmbeddingConfig.
type OptMultiEmbeddingConfig struct {
	Value MultiEmbeddingConfig
	Set   bool
}

// IsSet returns true if OptMultiEmbeddingConfig was set.
func (o OptMultiEmbeddingConfig) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMultiEmbeddingConfig) Reset() {
	var v MultiEmbeddingConfig
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMultiEmbeddingConfig) SetTo(v MultiEmbeddingConfig) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMultiEmbeddingConfig) Get() (v MultiEmbeddingConfig, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMultiEmbeddingConfig) Or(d MultiEmbeddingConfig) MultiEmbeddingConfig {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSparseEmbeddingConfig returns new OptSparseEmbeddingConfig with value set to v.
func NewOptSparseEmbeddingConfig(v SparseEmbeddingConfig) OptSparseEmbeddingConfig {
	return OptSparseEmbeddingConfig{
		Value: v,
		Set:   true,
	}
}

// OptSparseEmbeddingConfig is optional SparseEmbeddingConfig.
type OptSparseEmbeddingConfig struct {
	Value SparseEmbeddingConfig
	Set   bool
}

// IsSet returns true if OptSparseEmbeddingConfig was set.
func (o OptSparseEmbeddingConfig) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSparseEmbeddingConfig) Reset() {
	var v SparseEmbeddingConfig
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSparseEmbeddingConfig) SetTo(v SparseEmbeddingConfig) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSparseEmbeddingConfig) Get() (v SparseEmbeddingConfig, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSparseEmbeddingConfig) Or(d SparseEmbeddingConfig) SparseEmbeddingConfig {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSparseEmbeddingMode returns new OptSparseEmbeddingMode with value set to v.
func NewOptSparseEmbeddingMode(v SparseEmbeddingMode) OptSparseEmbeddingMode {
	return OptSparseEmbeddingMode{
		Value: v,
		Set:   true,
	}
}

// OptSparseEmbeddingMode is optional SparseEmbeddingMode.
type OptSparseEmbeddingMode struct {
	Value SparseEmbeddingMode
	Set   bool
}

// IsSet returns true if OptSparseEmbeddingMode was set.
func (o OptSparseEmbeddingMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSparseEmbeddingMode) Reset() {
	var v SparseEmbeddingMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSparseEmbeddingMode) SetTo(v SparseEmbeddingMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSparseEmbeddingMode) Get() (v SparseEmbeddingMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSparseEmbeddingMode) Or(d SparseEmbeddingMode) SparseEmbeddingMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptVideoURL returns new OptVideoURL with value set to v.
func NewOptVideoURL(v VideoURL) OptVideoURL {
	return OptVideoURL{
		Value: v,
		Set:   true,
	}
}

// OptVideoURL is optional VideoURL.
type OptVideoURL struct {
	Value VideoURL
	Set   bool
}

// IsSet returns true if OptVideoURL was set.
func (o OptVideoURL) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptVideoURL) Reset() {
	var v VideoURL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptVideoURL) SetTo(v VideoURL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptVideoURL) Get() (v VideoURL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptVideoURL) Or(d VideoURL) VideoURL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PromptTokensDetails
type PromptTokensDetails struct {
	// The number of prompt tokens consumed by text inputs.
	TextTokens int64 `json:"text_tokens"`
	// The number of prompt tokens consumed by image inputs.
	ImageTokens int64 `json:"image_tokens"`
}

// GetTextTokens returns the value of TextTokens.
func (s *PromptTokensDetails) GetTextTokens() int64 {
	return s.TextTokens
}

// GetImageTokens returns the value of ImageTokens.
func (s *PromptTokensDetails) GetImageTokens() int64 {
	return s.ImageTokens
}

// SetTextTokens sets the value of TextTokens.
func (s *PromptTokensDetails) SetTextTokens(val int64) {
	s.TextTokens = val
}

// SetImageTokens sets the value of ImageTokens.
func (s *PromptTokensDetails) SetImageTokens(val int64) {
	s.ImageTokens = val
}

// Ref: #/components/schemas/SparseEmbeddingConfig
type SparseEmbeddingConfig struct {
	// Whether sparse embeddings should be returned.
	Type OptSparseEmbeddingMode `json:"type"`
}

// GetType returns the value of Type.
func (s *SparseEmbeddingConfig) GetType() OptSparseEmbeddingMode {
	return s.Type
}

// SetType sets the value of Type.
func (s *SparseEmbeddingConfig) SetType(val OptSparseEmbeddingMode) {
	s.Type = val
}

// Ref: #/components/schemas/SparseEmbeddingMode
type SparseEmbeddingMode string

const (
	SparseEmbeddingModeEnabled  SparseEmbeddingMode = "enabled"
	SparseEmbeddingModeDisabled SparseEmbeddingMode = "disabled"
)

// AllValues returns all SparseEmbeddingMode values.
func (SparseEmbeddingMode) AllValues() []SparseEmbeddingMode {
	return []SparseEmbeddingMode{
		SparseEmbeddingModeEnabled,
		SparseEmbeddingModeDisabled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SparseEmbeddingMode) MarshalText() ([]byte, error) {
	switch s {
	case SparseEmbeddingModeEnabled:
		return []byte(s), nil
	case SparseEmbeddingModeDisabled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SparseEmbeddingMode) UnmarshalText(data []byte) error {
	switch SparseEmbeddingMode(data) {
	case SparseEmbeddingModeEnabled:
		*s = SparseEmbeddingModeEnabled
		return nil
	case SparseEmbeddingModeDisabled:
		*s = SparseEmbeddingModeDisabled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SparseEmbeddingValue
type SparseEmbeddingValue struct {
	// Index of the non-zero dimension.
	Index int64 `json:"index"`
	// Value at that dimension.
	Value float64 `json:"value"`
}

// GetIndex returns the value of Index.
func (s *SparseEmbeddingValue) GetIndex() int64 {
	return s.Index
}

// GetValue returns the value of Value.
func (s *SparseEmbeddingValue) GetValue() float64 {
	return s.Value
}

// SetIndex sets the value of Index.
func (s *SparseEmbeddingValue) SetIndex(val int64) {
	s.Index = val
}

// SetValue sets the value of Value.
func (s *SparseEmbeddingValue) SetValue(val float64) {
	s.Value = val
}

// Ref: #/components/schemas/VideoURL
type VideoURL struct {
	// The URL of the video to embed.
	URL string `json:"url"`
	// Frames-per-second sampling rate for the video.
	Fps OptFloat64 `json:"fps"`
}

// GetURL returns the value of URL.
func (s *VideoURL) GetURL() string {
	return s.URL
}

// GetFps returns the value of Fps.
func (s *VideoURL) GetFps() OptFloat64 {
	return s.Fps
}

// SetURL sets the value of URL.
func (s *VideoURL) SetURL(val string) {
	s.URL = val
}

// SetFps sets the value of Fps.
func (s *VideoURL) SetFps(val OptFloat64) {
	s.Fps = val
}
