// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package file

// FilesDeleteParams is parameters of Files_delete operation.
type FilesDeleteParams struct {
	FileID string
}

// FilesListParams is parameters of Files_list operation.
type FilesListParams struct {
	// Filter results to a single purpose.
	Purpose OptPurpose `json:",omitempty,omitzero" query:"purpose"`
	// Cursor (file id) for pagination — return items after this id.
	After OptString `json:",omitempty,omitzero" query:"after"`
	// Maximum number of items to return. Server-defined default and ceiling.
	Limit OptInt64 `json:",omitempty,omitzero" query:"limit"`
	// Sort order by `created_at`.
	Order OptOrder `json:",omitempty,omitzero" query:"order"`
}

// FilesRetrieveParams is parameters of Files_retrieve operation.
type FilesRetrieveParams struct {
	FileID string
}
