// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package messages

import (
	"github.com/volcengine/ark-runtime-go/arkruntime/internal/ogenregex"
)

var regexMap = map[string]ogenregex.Regexp{
	"^(clear_thinking|clear_tool_uses)": ogenregex.MustCompile("^(clear_thinking|clear_tool_uses)"),
}
