// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package messages

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/volcengine/ark-runtime-go/arkruntime/internal/validate"
)

func (s *ContentBlockStart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.ContentBlock.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content_block",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ContentBlockStartContentBlock) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ContentBlockStartContentBlockServerToolUse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ContentBlockStartContentBlockServerToolUseType) Validate() error {
	switch s {
	case "server_tool_use":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ContentBlockStartContentBlockSum) Validate() error {
	switch s.Type {
	case ContentBlockStartContentBlockTextContentBlockStartContentBlockSum:
		if err := s.ContentBlockStartContentBlockText.Validate(); err != nil {
			return err
		}
		return nil
	case ContentBlockStartContentBlockThinkingContentBlockStartContentBlockSum:
		if err := s.ContentBlockStartContentBlockThinking.Validate(); err != nil {
			return err
		}
		return nil
	case ContentBlockStartContentBlockToolUseContentBlockStartContentBlockSum:
		if err := s.ContentBlockStartContentBlockToolUse.Validate(); err != nil {
			return err
		}
		return nil
	case ContentBlockStartContentBlockServerToolUseContentBlockStartContentBlockSum:
		if err := s.ContentBlockStartContentBlockServerToolUse.Validate(); err != nil {
			return err
		}
		return nil
	case ContentBlockStartContentBlockWebSearchToolResultContentBlockStartContentBlockSum:
		if err := s.ContentBlockStartContentBlockWebSearchToolResult.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *ContentBlockStartContentBlockText) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ContentBlockStartContentBlockTextType) Validate() error {
	switch s {
	case "text":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ContentBlockStartContentBlockThinking) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ContentBlockStartContentBlockThinkingType) Validate() error {
	switch s {
	case "thinking":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ContentBlockStartContentBlockToolUse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ContentBlockStartContentBlockToolUseType) Validate() error {
	switch s {
	case "tool_use":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ContentBlockStartContentBlockWebSearchToolResult) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Content.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ContentBlockStartContentBlockWebSearchToolResultType) Validate() error {
	switch s {
	case "web_search_tool_result":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ContentBlockStartType) Validate() error {
	switch s {
	case "content_block_start":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesContentPart) Validate() error {
	switch s.Type {
	case MessagesContentPartTextMessagesContentPart:
		if err := s.MessagesContentPartText.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartThinkingMessagesContentPart:
		if err := s.MessagesContentPartThinking.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartImageMessagesContentPart:
		if err := s.MessagesContentPartImage.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartDocumentMessagesContentPart:
		if err := s.MessagesContentPartDocument.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartToolUseMessagesContentPart:
		if err := s.MessagesContentPartToolUse.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartToolResultMessagesContentPart:
		if err := s.MessagesContentPartToolResult.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartServerToolUseMessagesContentPart:
		if err := s.MessagesContentPartServerToolUse.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartWebSearchToolResultMessagesContentPart:
		if err := s.MessagesContentPartWebSearchToolResult.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesContentPartDocument) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Source.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "source",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesContentPartDocumentSource) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesContentPartDocumentSourceBase64) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Data)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartDocumentSourceBase64Type) Validate() error {
	switch s {
	case "base64":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartDocumentSourceContent) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Content.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartDocumentSourceContentType) Validate() error {
	switch s {
	case "content":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesContentPartDocumentSourceSum) Validate() error {
	switch s.Type {
	case MessagesContentPartDocumentSourceBase64MessagesContentPartDocumentSourceSum:
		if err := s.MessagesContentPartDocumentSourceBase64.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartDocumentSourceTextMessagesContentPartDocumentSourceSum:
		if err := s.MessagesContentPartDocumentSourceText.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartDocumentSourceUrlMessagesContentPartDocumentSourceSum:
		if err := s.MessagesContentPartDocumentSourceUrl.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartDocumentSourceContentMessagesContentPartDocumentSourceSum:
		if err := s.MessagesContentPartDocumentSourceContent.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesContentPartDocumentSourceText) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Data)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "data",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartDocumentSourceTextType) Validate() error {
	switch s {
	case "text":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartDocumentSourceUrl) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.URL)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "url",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartDocumentSourceUrlType) Validate() error {
	switch s {
	case "url":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesContentPartDocumentType) Validate() error {
	switch s {
	case "document":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartImage) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Source.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "source",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesContentPartImageSource) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartImageType) Validate() error {
	switch s {
	case "image":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartServerToolUse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.ID)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartServerToolUseType) Validate() error {
	switch s {
	case "server_tool_use":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartText) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartTextType) Validate() error {
	switch s {
	case "text":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartThinking) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartThinkingType) Validate() error {
	switch s {
	case "thinking":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartToolReference) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartToolReferenceType) Validate() error {
	switch s {
	case "tool_reference":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartToolResult) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Content.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartToolResultType) Validate() error {
	switch s {
	case "tool_result":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartToolUse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartToolUseType) Validate() error {
	switch s {
	case "tool_use":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContentPartWebSearchToolResult) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Content.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContentPartWebSearchToolResultType) Validate() error {
	switch s {
	case "web_search_tool_result":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContextManagement) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Edits.Get(); ok {
			if err := func() error {
				if value == nil {
					return errors.New("nil is invalid value")
				}
				var failures []validate.FieldError
				for i, elem := range value {
					if err := func() error {
						if err := elem.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						failures = append(failures, validate.FieldError{
							Name:  fmt.Sprintf("[%d]", i),
							Error: err,
						})
					}
				}
				if len(failures) > 0 {
					return &validate.Error{Fields: failures}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "edits",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesContextManagementEdit) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         regexMap["^(clear_thinking|clear_tool_uses)"],
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Type)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Keep.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "keep",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExcludeTools.Get(); ok {
			if err := func() error {
				if value == nil {
					return errors.New("nil is invalid value")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "exclude_tools",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContextManagementKeep) Validate() error {
	switch s.Type {
	case MessagesContextManagementKeep0MessagesContextManagementKeep:
		if err := s.MessagesContextManagementKeep0.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContextManagementKeepParameterMessagesContextManagementKeep:
		if err := s.MessagesContextManagementKeepParameter.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s MessagesContextManagementKeep0) Validate() error {
	switch s {
	case "all":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContextManagementKeepAll) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContextManagementKeepAllType) Validate() error {
	switch s {
	case "all":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContextManagementKeepParameter) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContextManagementKeepParameterSum) Validate() error {
	switch s.Type {
	case MessagesContextManagementKeepAllMessagesContextManagementKeepParameterSum:
		if err := s.MessagesContextManagementKeepAll.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContextManagementKeepThinkingTurnsMessagesContextManagementKeepParameterSum:
		if err := s.MessagesContextManagementKeepThinkingTurns.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContextManagementKeepToolUsesMessagesContextManagementKeepParameterSum:
		if err := s.MessagesContextManagementKeepToolUses.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesContextManagementKeepThinkingTurns) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContextManagementKeepThinkingTurnsType) Validate() error {
	switch s {
	case "thinking_turns":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesContextManagementKeepToolUses) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesContextManagementKeepToolUsesType) Validate() error {
	switch s {
	case "tool_uses":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesDocumentContent) Validate() error {
	switch s.Type {
	case MessagesDocumentContentTextMessagesDocumentContent:
		if err := s.MessagesDocumentContentText.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesDocumentContentPartsMessagesDocumentContent:
		if err := s.MessagesDocumentContentParts.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s MessagesDocumentContentParts) Validate() error {
	alias := ([]MessagesContentPart)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	if err := (validate.Array{
		MinLength:    1,
		MinLengthSet: true,
		MaxLength:    0,
		MaxLengthSet: false,
	}).ValidateLength(len(alias)); err != nil {
		return errors.Wrap(err, "array")
	}
	var failures []validate.FieldError
	for i, elem := range alias {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  fmt.Sprintf("[%d]", i),
				Error: err,
			})
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesDocumentContentText) Validate() error {
	alias := (string)(s)
	if err := (validate.String{
		MinLength:     1,
		MinLengthSet:  true,
		MaxLength:     0,
		MaxLengthSet:  false,
		Email:         false,
		Hostname:      false,
		Regex:         nil,
		MinNumeric:    0,
		MinNumericSet: false,
		MaxNumeric:    0,
		MaxNumericSet: false,
	}).Validate(string(alias)); err != nil {
		return errors.Wrap(err, "string")
	}
	return nil
}

func (s *MessagesErrorResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesErrorResponseType) Validate() error {
	switch s {
	case "error":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesFrequencyPenalty) Validate() error {
	alias := (float64)(s)
	if err := (validate.Float{
		MinSet:        true,
		Min:           -2,
		MaxSet:        true,
		Max:           2,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    nil,
		Pattern:       nil,
	}).Validate(float64(alias)); err != nil {
		return errors.Wrap(err, "float")
	}
	return nil
}

func (s MessagesImageSourceType) Validate() error {
	switch s {
	case "url":
		return nil
	case "base64":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesLogitBiasValue) Validate() error {
	alias := (float32)(s)
	if err := (validate.Float{
		MinSet:        true,
		Min:           -100,
		MaxSet:        true,
		Max:           100,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    nil,
		Pattern:       nil,
	}).Validate(float64(alias)); err != nil {
		return errors.Wrap(err, "float")
	}
	return nil
}

func (s MessagesMaxTokens) Validate() error {
	alias := (int32)(s)
	if err := (validate.Int{
		MinSet:        true,
		Min:           0,
		MaxSet:        false,
		Max:           0,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    0,
		Pattern:       nil,
	}).Validate(int64(alias)); err != nil {
		return errors.Wrap(err, "int")
	}
	return nil
}

func (s MessagesMaxUses) Validate() error {
	alias := (int32)(s)
	if err := (validate.Int{
		MinSet:        true,
		Min:           1,
		MaxSet:        false,
		Max:           0,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    0,
		Pattern:       nil,
	}).Validate(int64(alias)); err != nil {
		return errors.Wrap(err, "int")
	}
	return nil
}

func (s MessagesMessageContent) Validate() error {
	switch s.Type {
	case StringMessagesMessageContent:
		return nil // no validation needed
	case MessagesContentPartArrayMessagesMessageContent:
		if s.MessagesContentPartArray == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.MessagesContentPartArray {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesOutputFormat) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesOutputFormatJsonObject) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesOutputFormatJsonObjectType) Validate() error {
	switch s {
	case "json_object":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesOutputFormatJsonSchema) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesOutputFormatJsonSchemaType) Validate() error {
	switch s {
	case "json_schema":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesOutputFormatSum) Validate() error {
	switch s.Type {
	case MessagesOutputFormatTextMessagesOutputFormatSum:
		if err := s.MessagesOutputFormatText.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesOutputFormatJsonObjectMessagesOutputFormatSum:
		if err := s.MessagesOutputFormatJsonObject.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesOutputFormatJsonSchemaMessagesOutputFormatSum:
		if err := s.MessagesOutputFormatJsonSchema.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesOutputFormatText) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesOutputFormatTextType) Validate() error {
	switch s {
	case "text":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesPresencePenalty) Validate() error {
	alias := (float64)(s)
	if err := (validate.Float{
		MinSet:        true,
		Min:           -2,
		MaxSet:        true,
		Max:           2,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    nil,
		Pattern:       nil,
	}).Validate(float64(alias)); err != nil {
		return errors.Wrap(err, "float")
	}
	return nil
}

func (s MessagesRepetitionPenalty) Validate() error {
	alias := (float64)(s)
	if err := (validate.Float{
		MinSet:        true,
		Min:           0,
		MaxSet:        true,
		Max:           2,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    nil,
		Pattern:       nil,
	}).Validate(float64(alias)); err != nil {
		return errors.Wrap(err, "float")
	}
	return nil
}

func (s *MessagesRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Messages == nil {
			return errors.New("nil is invalid value")
		}
		if err := (validate.Array{
			MinLength:    1,
			MinLengthSet: true,
			MaxLength:    0,
			MaxLengthSet: false,
		}).ValidateLength(len(s.Messages)); err != nil {
			return errors.Wrap(err, "array")
		}
		var failures []validate.FieldError
		for i, elem := range s.Messages {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "messages",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.System.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "system",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.FrequencyPenalty.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "frequency_penalty",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.LogitBias.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "logit_bias",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.MaxTokens.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "max_tokens",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.PresencePenalty.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "presence_penalty",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.RepetitionPenalty.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "repetition_penalty",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.OutputFormat.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "output_format",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.StopSequences.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "stop_sequences",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Temperature.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "temperature",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ToolChoice.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "tool_choice",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Tools.Get(); ok {
			if err := func() error {
				if value == nil {
					return errors.New("nil is invalid value")
				}
				var failures []validate.FieldError
				for i, elem := range value {
					if err := func() error {
						if err := elem.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						failures = append(failures, validate.FieldError{
							Name:  fmt.Sprintf("[%d]", i),
							Error: err,
						})
					}
				}
				if len(failures) > 0 {
					return &validate.Error{Fields: failures}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "tools",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.TopLogprobs.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "top_logprobs",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.TopP.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "top_p",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ServiceTier.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "service_tier",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ContextManagement.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "context_management",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesRequestLogitBias) Validate() error {
	var failures []validate.FieldError
	for key, elem := range s {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  key,
				Error: err,
			})
		}
	}

	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesRequestMessage) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Role.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "role",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Content.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesRequestServiceTier) Validate() error {
	switch s {
	case "":
		return nil
	case "auto":
		return nil
	case "default":
		return nil
	case "flex":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Role.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "role",
			Error: err,
		})
	}
	if err := func() error {
		if s.Content == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Content {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.StopReason.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "stop_reason",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesResponseContentBlock) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Delta.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "delta",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesResponseContentBlockDelta) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesResponseContentBlockDeltaSignature) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentBlockDeltaSignatureType) Validate() error {
	switch s {
	case "signature_delta":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesResponseContentBlockDeltaSum) Validate() error {
	switch s.Type {
	case MessagesResponseContentBlockDeltaTextMessagesResponseContentBlockDeltaSum:
		if err := s.MessagesResponseContentBlockDeltaText.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentBlockDeltaThinkingMessagesResponseContentBlockDeltaSum:
		if err := s.MessagesResponseContentBlockDeltaThinking.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentBlockDeltaSignatureMessagesResponseContentBlockDeltaSum:
		if err := s.MessagesResponseContentBlockDeltaSignature.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentBlockDeltaToolUseMessagesResponseContentBlockDeltaSum:
		if err := s.MessagesResponseContentBlockDeltaToolUse.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesResponseContentBlockDeltaText) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentBlockDeltaTextType) Validate() error {
	switch s {
	case "text_delta":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseContentBlockDeltaThinking) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentBlockDeltaThinkingType) Validate() error {
	switch s {
	case "thinking_delta":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseContentBlockDeltaToolUse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentBlockDeltaToolUseType) Validate() error {
	switch s {
	case "input_json_delta":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseContentBlockStop) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentBlockStopType) Validate() error {
	switch s {
	case "content_block_stop":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesResponseContentBlockType) Validate() error {
	switch s {
	case "content_block_delta":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseContentPart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesResponseContentPartServerToolUse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentPartServerToolUseType) Validate() error {
	switch s {
	case "server_tool_use":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesResponseContentPartSum) Validate() error {
	switch s.Type {
	case MessagesResponseContentPartTextMessagesResponseContentPartSum:
		if err := s.MessagesResponseContentPartText.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentPartThinkingMessagesResponseContentPartSum:
		if err := s.MessagesResponseContentPartThinking.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentPartToolUseMessagesResponseContentPartSum:
		if err := s.MessagesResponseContentPartToolUse.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentPartServerToolUseMessagesResponseContentPartSum:
		if err := s.MessagesResponseContentPartServerToolUse.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentPartWebSearchToolResultMessagesResponseContentPartSum:
		if err := s.MessagesResponseContentPartWebSearchToolResult.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesResponseContentPartText) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentPartTextType) Validate() error {
	switch s {
	case "text":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseContentPartThinking) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentPartThinkingType) Validate() error {
	switch s {
	case "thinking":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseContentPartToolUse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentPartToolUseType) Validate() error {
	switch s {
	case "tool_use":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseContentPartWebSearchToolResult) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Content.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseContentPartWebSearchToolResultType) Validate() error {
	switch s {
	case "web_search_tool_result":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesResponseRole) Validate() error {
	switch s {
	case "assistant":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesResponseStopReason) Validate() error {
	switch s {
	case "end_turn":
		return nil
	case "max_tokens":
		return nil
	case "stop_sequence":
		return nil
	case "tool_use":
		return nil
	case "pause_turn":
		return nil
	case "refusal":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseStreamMessageDelta) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Delta.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "delta",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesResponseStreamMessageDeltaDelta) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.StopReason.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "stop_reason",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseStreamMessageDeltaType) Validate() error {
	switch s {
	case "message_delta":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseStreamMessageStart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Message.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "message",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesResponseStreamMessageStartMessage) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Role.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "role",
			Error: err,
		})
	}
	if err := func() error {
		if s.Content == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "content",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.StopReason.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "stop_reason",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseStreamMessageStartMessageRole) Validate() error {
	switch s {
	case "assistant":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesResponseStreamMessageStartMessageType) Validate() error {
	switch s {
	case "message":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesResponseStreamMessageStartType) Validate() error {
	switch s {
	case "message_start":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesResponseStreamMessageStop) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesResponseStreamMessageStopType) Validate() error {
	switch s {
	case "message_stop":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesResponseType) Validate() error {
	switch s {
	case "message":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesRole) Validate() error {
	alias := (string)(s)
	if err := (validate.String{
		MinLength:     1,
		MinLengthSet:  true,
		MaxLength:     0,
		MaxLengthSet:  false,
		Email:         false,
		Hostname:      false,
		Regex:         nil,
		MinNumeric:    0,
		MinNumericSet: false,
		MaxNumeric:    0,
		MaxNumericSet: false,
	}).Validate(string(alias)); err != nil {
		return errors.Wrap(err, "string")
	}
	return nil
}

func (s MessagesStopSequences) Validate() error {
	switch s.Type {
	case StringMessagesStopSequences:
		return nil // no validation needed
	case StringArrayMessagesStopSequences:
		if s.StringArray == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	case NullMessagesStopSequences:
		return nil // no validation needed
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesStreamEvent) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesStreamEventSum) Validate() error {
	switch s.Type {
	case MessagesResponseStreamMessageStartMessagesStreamEventSum:
		if err := s.MessagesResponseStreamMessageStart.Validate(); err != nil {
			return err
		}
		return nil
	case ContentBlockStartMessagesStreamEventSum:
		if err := s.ContentBlockStart.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentBlockMessagesStreamEventSum:
		if err := s.MessagesResponseContentBlock.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseContentBlockStopMessagesStreamEventSum:
		if err := s.MessagesResponseContentBlockStop.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseStreamMessageDeltaMessagesStreamEventSum:
		if err := s.MessagesResponseStreamMessageDelta.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesResponseStreamMessageStopMessagesStreamEventSum:
		if err := s.MessagesResponseStreamMessageStop.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesErrorResponseMessagesStreamEventSum:
		if err := s.MessagesErrorResponse.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s MessagesSystem) Validate() error {
	switch s.Type {
	case StringMessagesSystem:
		return nil // no validation needed
	case MessagesSystemTextPartArrayMessagesSystem:
		if s.MessagesSystemTextPartArray == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.MessagesSystemTextPartArray {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesSystemTextPart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesSystemTextPartType) Validate() error {
	switch s {
	case "text":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesTemperature) Validate() error {
	alias := (float64)(s)
	if err := (validate.Float{
		MinSet:        true,
		Min:           0,
		MaxSet:        true,
		Max:           2,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    nil,
		Pattern:       nil,
	}).Validate(float64(alias)); err != nil {
		return errors.Wrap(err, "float")
	}
	return nil
}

func (s *MessagesTool) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.MaxUses.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "max_uses",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.AllowedDomains.Get(); ok {
			if err := func() error {
				if value == nil {
					return errors.New("nil is invalid value")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "allowed_domains",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.BlockedDomains.Get(); ok {
			if err := func() error {
				if value == nil {
					return errors.New("nil is invalid value")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "blocked_domains",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesToolChoice) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MessagesToolChoiceAny) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesToolChoiceAnyType) Validate() error {
	switch s {
	case "any":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesToolChoiceAuto) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesToolChoiceAutoType) Validate() error {
	switch s {
	case "auto":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MessagesToolChoiceNone) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesToolChoiceNoneType) Validate() error {
	switch s {
	case "none":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesToolChoiceSum) Validate() error {
	switch s.Type {
	case MessagesToolChoiceAutoMessagesToolChoiceSum:
		if err := s.MessagesToolChoiceAuto.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesToolChoiceAnyMessagesToolChoiceSum:
		if err := s.MessagesToolChoiceAny.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesToolChoiceNoneMessagesToolChoiceSum:
		if err := s.MessagesToolChoiceNone.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesToolChoiceToolMessagesToolChoiceSum:
		if err := s.MessagesToolChoiceTool.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesToolChoiceTool) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesToolChoiceToolType) Validate() error {
	switch s {
	case "tool":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesToolResultContent) Validate() error {
	switch s.Type {
	case StringMessagesToolResultContent:
		return nil // no validation needed
	case MessagesToolResultContentPartArrayMessagesToolResultContent:
		if s.MessagesToolResultContentPartArray == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.MessagesToolResultContentPartArray {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesToolResultContentPart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.OneOf.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "OneOf",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesToolResultContentPartSum) Validate() error {
	switch s.Type {
	case MessagesContentPartTextMessagesToolResultContentPartSum:
		if err := s.MessagesContentPartText.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartImageMessagesToolResultContentPartSum:
		if err := s.MessagesContentPartImage.Validate(); err != nil {
			return err
		}
		return nil
	case MessagesContentPartToolReferenceMessagesToolResultContentPartSum:
		if err := s.MessagesContentPartToolReference.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s MessagesTopLogprobs) Validate() error {
	alias := (int32)(s)
	if err := (validate.Int{
		MinSet:        true,
		Min:           0,
		MaxSet:        true,
		Max:           20,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    0,
		Pattern:       nil,
	}).Validate(int64(alias)); err != nil {
		return errors.Wrap(err, "int")
	}
	return nil
}

func (s MessagesTopP) Validate() error {
	alias := (float64)(s)
	if err := (validate.Float{
		MinSet:        true,
		Min:           0,
		MaxSet:        true,
		Max:           1,
		MinExclusive:  false,
		MaxExclusive:  false,
		MultipleOfSet: false,
		MultipleOf:    nil,
		Pattern:       nil,
	}).Validate(float64(alias)); err != nil {
		return errors.Wrap(err, "float")
	}
	return nil
}

func (s *MessagesWebSearchResult) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesWebSearchResultType) Validate() error {
	switch s {
	case "web_search_result":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s MessagesWebSearchToolResultContent) Validate() error {
	switch s.Type {
	case MessagesWebSearchResultArrayMessagesWebSearchToolResultContent:
		if s.MessagesWebSearchResultArray == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.MessagesWebSearchResultArray {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	case MessagesWebSearchToolResultErrorMessagesWebSearchToolResultContent:
		if err := s.MessagesWebSearchToolResultError.Validate(); err != nil {
			return err
		}
		return nil
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}

func (s *MessagesWebSearchToolResultError) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.ErrorCode)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "error_code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s MessagesWebSearchToolResultErrorType) Validate() error {
	switch s {
	case "web_search_tool_result_error":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
