// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package contentgeneration

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/AudioURL
type AudioURL struct {
	// URL of the audio asset.
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *AudioURL) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *AudioURL) SetURL(val string) {
	s.URL = val
}

// Snapshot of a content-generation task.
// Ref: #/components/schemas/ContentGenerationTask
type ContentGenerationTask struct {
	// Task identifier.
	ID string `json:"id"`
	// Model used to produce the result.
	Model string `json:"model"`
	// Lifecycle state.
	Status TaskStatus `json:"status"`
	// Populated when the task ended in `failed`.
	Error OptTaskError `json:"error"`
	// Generated artifact URLs. Populated when the task succeeded.
	Content OptTaskContent `json:"content"`
	// Token / tool usage. Populated when the task is in a terminal state.
	Usage OptTaskUsage `json:"usage"`
	// Unix timestamp (seconds) when the task was created.
	CreatedAt OptInt64 `json:"created_at"`
	// Unix timestamp (seconds) when the task last changed.
	UpdatedAt OptInt64 `json:"updated_at"`
	// Random seed actually used by the algorithm.
	Seed OptInt64 `json:"seed"`
	// Resolution of the generated output.
	Resolution OptString `json:"resolution"`
	// Aspect ratio of the generated output.
	Ratio OptString `json:"ratio"`
	// Duration of the generated output (seconds).
	Duration OptInt64 `json:"duration"`
	// Frame count of the generated output.
	Frames OptInt64 `json:"frames"`
	// Frames-per-second of the generated output.
	Framespersecond OptInt64 `json:"framespersecond"`
	// Server-side rewritten prompt, when prompt optimization ran.
	RevisedPrompt OptString `json:"revised_prompt"`
	// Render-quality tier echoed back.
	Subdivisionlevel OptString `json:"subdivisionlevel"`
	// File format echoed back.
	Fileformat OptString `json:"fileformat"`
	// Service tier the task was scheduled on.
	ServiceTier OptString `json:"service_tier"`
	// Soft execution deadline echoed back.
	ExecutionExpiresAfter OptInt64 `json:"execution_expires_after"`
	// Whether audio was generated.
	GenerateAudio OptBool `json:"generate_audio"`
	// Whether this task is a draft.
	Draft OptBool `json:"draft"`
	// When this task is a refinement, the upstream draft id.
	DraftTaskID OptString `json:"draft_task_id"`
	// Tools that were enabled for the task.
	Tools []Tool `json:"tools"`
	// Reasoning effort echoed back.
	ReasoningEffort OptReasoningEffort `json:"reasoning_effort"`
	// Safety identifier echoed back.
	SafetyIdentifier OptString `json:"safety_identifier"`
}

// GetID returns the value of ID.
func (s *ContentGenerationTask) GetID() string {
	return s.ID
}

// GetModel returns the value of Model.
func (s *ContentGenerationTask) GetModel() string {
	return s.Model
}

// GetStatus returns the value of Status.
func (s *ContentGenerationTask) GetStatus() TaskStatus {
	return s.Status
}

// GetError returns the value of Error.
func (s *ContentGenerationTask) GetError() OptTaskError {
	return s.Error
}

// GetContent returns the value of Content.
func (s *ContentGenerationTask) GetContent() OptTaskContent {
	return s.Content
}

// GetUsage returns the value of Usage.
func (s *ContentGenerationTask) GetUsage() OptTaskUsage {
	return s.Usage
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ContentGenerationTask) GetCreatedAt() OptInt64 {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ContentGenerationTask) GetUpdatedAt() OptInt64 {
	return s.UpdatedAt
}

// GetSeed returns the value of Seed.
func (s *ContentGenerationTask) GetSeed() OptInt64 {
	return s.Seed
}

// GetResolution returns the value of Resolution.
func (s *ContentGenerationTask) GetResolution() OptString {
	return s.Resolution
}

// GetRatio returns the value of Ratio.
func (s *ContentGenerationTask) GetRatio() OptString {
	return s.Ratio
}

// GetDuration returns the value of Duration.
func (s *ContentGenerationTask) GetDuration() OptInt64 {
	return s.Duration
}

// GetFrames returns the value of Frames.
func (s *ContentGenerationTask) GetFrames() OptInt64 {
	return s.Frames
}

// GetFramespersecond returns the value of Framespersecond.
func (s *ContentGenerationTask) GetFramespersecond() OptInt64 {
	return s.Framespersecond
}

// GetRevisedPrompt returns the value of RevisedPrompt.
func (s *ContentGenerationTask) GetRevisedPrompt() OptString {
	return s.RevisedPrompt
}

// GetSubdivisionlevel returns the value of Subdivisionlevel.
func (s *ContentGenerationTask) GetSubdivisionlevel() OptString {
	return s.Subdivisionlevel
}

// GetFileformat returns the value of Fileformat.
func (s *ContentGenerationTask) GetFileformat() OptString {
	return s.Fileformat
}

// GetServiceTier returns the value of ServiceTier.
func (s *ContentGenerationTask) GetServiceTier() OptString {
	return s.ServiceTier
}

// GetExecutionExpiresAfter returns the value of ExecutionExpiresAfter.
func (s *ContentGenerationTask) GetExecutionExpiresAfter() OptInt64 {
	return s.ExecutionExpiresAfter
}

// GetGenerateAudio returns the value of GenerateAudio.
func (s *ContentGenerationTask) GetGenerateAudio() OptBool {
	return s.GenerateAudio
}

// GetDraft returns the value of Draft.
func (s *ContentGenerationTask) GetDraft() OptBool {
	return s.Draft
}

// GetDraftTaskID returns the value of DraftTaskID.
func (s *ContentGenerationTask) GetDraftTaskID() OptString {
	return s.DraftTaskID
}

// GetTools returns the value of Tools.
func (s *ContentGenerationTask) GetTools() []Tool {
	return s.Tools
}

// GetReasoningEffort returns the value of ReasoningEffort.
func (s *ContentGenerationTask) GetReasoningEffort() OptReasoningEffort {
	return s.ReasoningEffort
}

// GetSafetyIdentifier returns the value of SafetyIdentifier.
func (s *ContentGenerationTask) GetSafetyIdentifier() OptString {
	return s.SafetyIdentifier
}

// SetID sets the value of ID.
func (s *ContentGenerationTask) SetID(val string) {
	s.ID = val
}

// SetModel sets the value of Model.
func (s *ContentGenerationTask) SetModel(val string) {
	s.Model = val
}

// SetStatus sets the value of Status.
func (s *ContentGenerationTask) SetStatus(val TaskStatus) {
	s.Status = val
}

// SetError sets the value of Error.
func (s *ContentGenerationTask) SetError(val OptTaskError) {
	s.Error = val
}

// SetContent sets the value of Content.
func (s *ContentGenerationTask) SetContent(val OptTaskContent) {
	s.Content = val
}

// SetUsage sets the value of Usage.
func (s *ContentGenerationTask) SetUsage(val OptTaskUsage) {
	s.Usage = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ContentGenerationTask) SetCreatedAt(val OptInt64) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ContentGenerationTask) SetUpdatedAt(val OptInt64) {
	s.UpdatedAt = val
}

// SetSeed sets the value of Seed.
func (s *ContentGenerationTask) SetSeed(val OptInt64) {
	s.Seed = val
}

// SetResolution sets the value of Resolution.
func (s *ContentGenerationTask) SetResolution(val OptString) {
	s.Resolution = val
}

// SetRatio sets the value of Ratio.
func (s *ContentGenerationTask) SetRatio(val OptString) {
	s.Ratio = val
}

// SetDuration sets the value of Duration.
func (s *ContentGenerationTask) SetDuration(val OptInt64) {
	s.Duration = val
}

// SetFrames sets the value of Frames.
func (s *ContentGenerationTask) SetFrames(val OptInt64) {
	s.Frames = val
}

// SetFramespersecond sets the value of Framespersecond.
func (s *ContentGenerationTask) SetFramespersecond(val OptInt64) {
	s.Framespersecond = val
}

// SetRevisedPrompt sets the value of RevisedPrompt.
func (s *ContentGenerationTask) SetRevisedPrompt(val OptString) {
	s.RevisedPrompt = val
}

// SetSubdivisionlevel sets the value of Subdivisionlevel.
func (s *ContentGenerationTask) SetSubdivisionlevel(val OptString) {
	s.Subdivisionlevel = val
}

// SetFileformat sets the value of Fileformat.
func (s *ContentGenerationTask) SetFileformat(val OptString) {
	s.Fileformat = val
}

// SetServiceTier sets the value of ServiceTier.
func (s *ContentGenerationTask) SetServiceTier(val OptString) {
	s.ServiceTier = val
}

// SetExecutionExpiresAfter sets the value of ExecutionExpiresAfter.
func (s *ContentGenerationTask) SetExecutionExpiresAfter(val OptInt64) {
	s.ExecutionExpiresAfter = val
}

// SetGenerateAudio sets the value of GenerateAudio.
func (s *ContentGenerationTask) SetGenerateAudio(val OptBool) {
	s.GenerateAudio = val
}

// SetDraft sets the value of Draft.
func (s *ContentGenerationTask) SetDraft(val OptBool) {
	s.Draft = val
}

// SetDraftTaskID sets the value of DraftTaskID.
func (s *ContentGenerationTask) SetDraftTaskID(val OptString) {
	s.DraftTaskID = val
}

// SetTools sets the value of Tools.
func (s *ContentGenerationTask) SetTools(val []Tool) {
	s.Tools = val
}

// SetReasoningEffort sets the value of ReasoningEffort.
func (s *ContentGenerationTask) SetReasoningEffort(val OptReasoningEffort) {
	s.ReasoningEffort = val
}

// SetSafetyIdentifier sets the value of SafetyIdentifier.
func (s *ContentGenerationTask) SetSafetyIdentifier(val OptString) {
	s.SafetyIdentifier = val
}

// ContentGenerationTasksDeleteNoContent is response for ContentGenerationTasksDelete operation.
type ContentGenerationTasksDeleteNoContent struct{}

// One element of a generation request `content` list. Exactly one of
// `text` / `image_url` / `video_url` / `audio_url` / `draft_task` must be
// set, matching the value of `type`.
// Ref: #/components/schemas/ContentItem
type ContentItem struct {
	// Discriminator for which payload field is set.
	Type ContentType `json:"type"`
	// Text content. Required when `type` is `text`.
	Text OptString `json:"text"`
	// Image content. Required when `type` is `image_url`.
	ImageURL OptImageURL `json:"image_url"`
	// Video content. Required when `type` is `video_url`.
	VideoURL OptVideoURL `json:"video_url"`
	// Audio content. Required when `type` is `audio_url`.
	AudioURL OptAudioURL `json:"audio_url"`
	// Draft-task reference. Required when `type` is `draft_task`.
	DraftTask OptDraftTask `json:"draft_task"`
	// Optional role tag (e.g. `first_frame`, `reference_image`).
	Role OptString `json:"role"`
}

// GetType returns the value of Type.
func (s *ContentItem) GetType() ContentType {
	return s.Type
}

// GetText returns the value of Text.
func (s *ContentItem) GetText() OptString {
	return s.Text
}

// GetImageURL returns the value of ImageURL.
func (s *ContentItem) GetImageURL() OptImageURL {
	return s.ImageURL
}

// GetVideoURL returns the value of VideoURL.
func (s *ContentItem) GetVideoURL() OptVideoURL {
	return s.VideoURL
}

// GetAudioURL returns the value of AudioURL.
func (s *ContentItem) GetAudioURL() OptAudioURL {
	return s.AudioURL
}

// GetDraftTask returns the value of DraftTask.
func (s *ContentItem) GetDraftTask() OptDraftTask {
	return s.DraftTask
}

// GetRole returns the value of Role.
func (s *ContentItem) GetRole() OptString {
	return s.Role
}

// SetType sets the value of Type.
func (s *ContentItem) SetType(val ContentType) {
	s.Type = val
}

// SetText sets the value of Text.
func (s *ContentItem) SetText(val OptString) {
	s.Text = val
}

// SetImageURL sets the value of ImageURL.
func (s *ContentItem) SetImageURL(val OptImageURL) {
	s.ImageURL = val
}

// SetVideoURL sets the value of VideoURL.
func (s *ContentItem) SetVideoURL(val OptVideoURL) {
	s.VideoURL = val
}

// SetAudioURL sets the value of AudioURL.
func (s *ContentItem) SetAudioURL(val OptAudioURL) {
	s.AudioURL = val
}

// SetDraftTask sets the value of DraftTask.
func (s *ContentItem) SetDraftTask(val OptDraftTask) {
	s.DraftTask = val
}

// SetRole sets the value of Role.
func (s *ContentItem) SetRole(val OptString) {
	s.Role = val
}

// Discriminator for an entry in the request `content` list.
// Ref: #/components/schemas/ContentType
type ContentType string

const (
	ContentTypeText      ContentType = "text"
	ContentTypeImageURL  ContentType = "image_url"
	ContentTypeVideoURL  ContentType = "video_url"
	ContentTypeAudioURL  ContentType = "audio_url"
	ContentTypeDraftTask ContentType = "draft_task"
)

// AllValues returns all ContentType values.
func (ContentType) AllValues() []ContentType {
	return []ContentType{
		ContentTypeText,
		ContentTypeImageURL,
		ContentTypeVideoURL,
		ContentTypeAudioURL,
		ContentTypeDraftTask,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ContentType) MarshalText() ([]byte, error) {
	switch s {
	case ContentTypeText:
		return []byte(s), nil
	case ContentTypeImageURL:
		return []byte(s), nil
	case ContentTypeVideoURL:
		return []byte(s), nil
	case ContentTypeAudioURL:
		return []byte(s), nil
	case ContentTypeDraftTask:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ContentType) UnmarshalText(data []byte) error {
	switch ContentType(data) {
	case ContentTypeText:
		*s = ContentTypeText
		return nil
	case ContentTypeImageURL:
		*s = ContentTypeImageURL
		return nil
	case ContentTypeVideoURL:
		*s = ContentTypeVideoURL
		return nil
	case ContentTypeAudioURL:
		*s = ContentTypeAudioURL
		return nil
	case ContentTypeDraftTask:
		*s = ContentTypeDraftTask
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CreateContentGenerationTaskRequest
type CreateContentGenerationTaskRequest struct {
	// The model identifier to use.
	Model string `json:"model"`
	// Ordered list of content inputs (text / image / video / audio / draft).
	Content []ContentItem `json:"content"`
	// Webhook URL invoked when the task transitions to a terminal state.
	CallbackURL OptString `json:"callback_url"`
	// Whether to also return a still of the last generated frame.
	ReturnLastFrame OptBool `json:"return_last_frame"`
	// Service tier hint (e.g. `default`, `priority`).
	ServiceTier OptString `json:"service_tier"`
	// Soft execution deadline in seconds since task creation.
	ExecutionExpiresAfter OptInt64 `json:"execution_expires_after"`
	// Generate audio alongside the video.
	GenerateAudio OptBool `json:"generate_audio"`
	// Lock the camera; disables motion.
	CameraFixed OptBool `json:"camera_fixed"`
	// Embed a watermark in the generated video.
	Watermark OptBool `json:"watermark"`
	// Random seed for reproducible generation.
	Seed OptInt64 `json:"seed"`
	// Output resolution (e.g. `720p`, `1080p`).
	Resolution OptString `json:"resolution"`
	// Output aspect ratio (e.g. `16:9`).
	Ratio OptString `json:"ratio"`
	// Duration of the generated video in seconds.
	Duration OptInt64 `json:"duration"`
	// Total number of frames (alternative to `duration`).
	Frames OptInt64 `json:"frames"`
	// Render-quality tier (e.g. `high`, `medium`, `low`).
	SubdivisionLevel OptString `json:"subdivision_level"`
	// Output file format (e.g. `mp4`, `glb`).
	FileFormat OptString `json:"file_format"`
	// Mark this task as a draft (cheaper, lower-quality).
	Draft OptBool `json:"draft"`
	// Run the prompt-optimization pass before generation.
	OptimizePrompt OptBool `json:"optimize_prompt"`
	// Tools the model may invoke during generation.
	Tools []Tool `json:"tools"`
	// Hint for how much reasoning the model should do.
	ReasoningEffort OptReasoningEffort `json:"reasoning_effort"`
	// Human-face handling mode (e.g. `strict`, `relaxed`).
	HumanFaceMode OptString `json:"human_face_mode"`
	// End-user identifier for safety/abuse signals.
	SafetyIdentifier OptString `json:"safety_identifier"`
}

// GetModel returns the value of Model.
func (s *CreateContentGenerationTaskRequest) GetModel() string {
	return s.Model
}

// GetContent returns the value of Content.
func (s *CreateContentGenerationTaskRequest) GetContent() []ContentItem {
	return s.Content
}

// GetCallbackURL returns the value of CallbackURL.
func (s *CreateContentGenerationTaskRequest) GetCallbackURL() OptString {
	return s.CallbackURL
}

// GetReturnLastFrame returns the value of ReturnLastFrame.
func (s *CreateContentGenerationTaskRequest) GetReturnLastFrame() OptBool {
	return s.ReturnLastFrame
}

// GetServiceTier returns the value of ServiceTier.
func (s *CreateContentGenerationTaskRequest) GetServiceTier() OptString {
	return s.ServiceTier
}

// GetExecutionExpiresAfter returns the value of ExecutionExpiresAfter.
func (s *CreateContentGenerationTaskRequest) GetExecutionExpiresAfter() OptInt64 {
	return s.ExecutionExpiresAfter
}

// GetGenerateAudio returns the value of GenerateAudio.
func (s *CreateContentGenerationTaskRequest) GetGenerateAudio() OptBool {
	return s.GenerateAudio
}

// GetCameraFixed returns the value of CameraFixed.
func (s *CreateContentGenerationTaskRequest) GetCameraFixed() OptBool {
	return s.CameraFixed
}

// GetWatermark returns the value of Watermark.
func (s *CreateContentGenerationTaskRequest) GetWatermark() OptBool {
	return s.Watermark
}

// GetSeed returns the value of Seed.
func (s *CreateContentGenerationTaskRequest) GetSeed() OptInt64 {
	return s.Seed
}

// GetResolution returns the value of Resolution.
func (s *CreateContentGenerationTaskRequest) GetResolution() OptString {
	return s.Resolution
}

// GetRatio returns the value of Ratio.
func (s *CreateContentGenerationTaskRequest) GetRatio() OptString {
	return s.Ratio
}

// GetDuration returns the value of Duration.
func (s *CreateContentGenerationTaskRequest) GetDuration() OptInt64 {
	return s.Duration
}

// GetFrames returns the value of Frames.
func (s *CreateContentGenerationTaskRequest) GetFrames() OptInt64 {
	return s.Frames
}

// GetSubdivisionLevel returns the value of SubdivisionLevel.
func (s *CreateContentGenerationTaskRequest) GetSubdivisionLevel() OptString {
	return s.SubdivisionLevel
}

// GetFileFormat returns the value of FileFormat.
func (s *CreateContentGenerationTaskRequest) GetFileFormat() OptString {
	return s.FileFormat
}

// GetDraft returns the value of Draft.
func (s *CreateContentGenerationTaskRequest) GetDraft() OptBool {
	return s.Draft
}

// GetOptimizePrompt returns the value of OptimizePrompt.
func (s *CreateContentGenerationTaskRequest) GetOptimizePrompt() OptBool {
	return s.OptimizePrompt
}

// GetTools returns the value of Tools.
func (s *CreateContentGenerationTaskRequest) GetTools() []Tool {
	return s.Tools
}

// GetReasoningEffort returns the value of ReasoningEffort.
func (s *CreateContentGenerationTaskRequest) GetReasoningEffort() OptReasoningEffort {
	return s.ReasoningEffort
}

// GetHumanFaceMode returns the value of HumanFaceMode.
func (s *CreateContentGenerationTaskRequest) GetHumanFaceMode() OptString {
	return s.HumanFaceMode
}

// GetSafetyIdentifier returns the value of SafetyIdentifier.
func (s *CreateContentGenerationTaskRequest) GetSafetyIdentifier() OptString {
	return s.SafetyIdentifier
}

// SetModel sets the value of Model.
func (s *CreateContentGenerationTaskRequest) SetModel(val string) {
	s.Model = val
}

// SetContent sets the value of Content.
func (s *CreateContentGenerationTaskRequest) SetContent(val []ContentItem) {
	s.Content = val
}

// SetCallbackURL sets the value of CallbackURL.
func (s *CreateContentGenerationTaskRequest) SetCallbackURL(val OptString) {
	s.CallbackURL = val
}

// SetReturnLastFrame sets the value of ReturnLastFrame.
func (s *CreateContentGenerationTaskRequest) SetReturnLastFrame(val OptBool) {
	s.ReturnLastFrame = val
}

// SetServiceTier sets the value of ServiceTier.
func (s *CreateContentGenerationTaskRequest) SetServiceTier(val OptString) {
	s.ServiceTier = val
}

// SetExecutionExpiresAfter sets the value of ExecutionExpiresAfter.
func (s *CreateContentGenerationTaskRequest) SetExecutionExpiresAfter(val OptInt64) {
	s.ExecutionExpiresAfter = val
}

// SetGenerateAudio sets the value of GenerateAudio.
func (s *CreateContentGenerationTaskRequest) SetGenerateAudio(val OptBool) {
	s.GenerateAudio = val
}

// SetCameraFixed sets the value of CameraFixed.
func (s *CreateContentGenerationTaskRequest) SetCameraFixed(val OptBool) {
	s.CameraFixed = val
}

// SetWatermark sets the value of Watermark.
func (s *CreateContentGenerationTaskRequest) SetWatermark(val OptBool) {
	s.Watermark = val
}

// SetSeed sets the value of Seed.
func (s *CreateContentGenerationTaskRequest) SetSeed(val OptInt64) {
	s.Seed = val
}

// SetResolution sets the value of Resolution.
func (s *CreateContentGenerationTaskRequest) SetResolution(val OptString) {
	s.Resolution = val
}

// SetRatio sets the value of Ratio.
func (s *CreateContentGenerationTaskRequest) SetRatio(val OptString) {
	s.Ratio = val
}

// SetDuration sets the value of Duration.
func (s *CreateContentGenerationTaskRequest) SetDuration(val OptInt64) {
	s.Duration = val
}

// SetFrames sets the value of Frames.
func (s *CreateContentGenerationTaskRequest) SetFrames(val OptInt64) {
	s.Frames = val
}

// SetSubdivisionLevel sets the value of SubdivisionLevel.
func (s *CreateContentGenerationTaskRequest) SetSubdivisionLevel(val OptString) {
	s.SubdivisionLevel = val
}

// SetFileFormat sets the value of FileFormat.
func (s *CreateContentGenerationTaskRequest) SetFileFormat(val OptString) {
	s.FileFormat = val
}

// SetDraft sets the value of Draft.
func (s *CreateContentGenerationTaskRequest) SetDraft(val OptBool) {
	s.Draft = val
}

// SetOptimizePrompt sets the value of OptimizePrompt.
func (s *CreateContentGenerationTaskRequest) SetOptimizePrompt(val OptBool) {
	s.OptimizePrompt = val
}

// SetTools sets the value of Tools.
func (s *CreateContentGenerationTaskRequest) SetTools(val []Tool) {
	s.Tools = val
}

// SetReasoningEffort sets the value of ReasoningEffort.
func (s *CreateContentGenerationTaskRequest) SetReasoningEffort(val OptReasoningEffort) {
	s.ReasoningEffort = val
}

// SetHumanFaceMode sets the value of HumanFaceMode.
func (s *CreateContentGenerationTaskRequest) SetHumanFaceMode(val OptString) {
	s.HumanFaceMode = val
}

// SetSafetyIdentifier sets the value of SafetyIdentifier.
func (s *CreateContentGenerationTaskRequest) SetSafetyIdentifier(val OptString) {
	s.SafetyIdentifier = val
}

// Ref: #/components/schemas/CreateContentGenerationTaskResponse
type CreateContentGenerationTaskResponse struct {
	// Identifier of the newly created task.
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *CreateContentGenerationTaskResponse) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *CreateContentGenerationTaskResponse) SetID(val string) {
	s.ID = val
}

// Ref: #/components/schemas/DraftTask
type DraftTask struct {
	// Identifier of the draft task to refine.
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *DraftTask) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *DraftTask) SetID(val string) {
	s.ID = val
}

// Ref: #/components/schemas/ImageURL
type ImageURL struct {
	// URL of the image.
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *ImageURL) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *ImageURL) SetURL(val string) {
	s.URL = val
}

// Ref: #/components/schemas/ListContentGenerationTasksResponse
type ListContentGenerationTasksResponse struct {
	// Total number of tasks matching the filter (across all pages).
	Total int32 `json:"total"`
	// Page of tasks.
	Items []ContentGenerationTask `json:"items"`
}

// GetTotal returns the value of Total.
func (s *ListContentGenerationTasksResponse) GetTotal() int32 {
	return s.Total
}

// GetItems returns the value of Items.
func (s *ListContentGenerationTasksResponse) GetItems() []ContentGenerationTask {
	return s.Items
}

// SetTotal sets the value of Total.
func (s *ListContentGenerationTasksResponse) SetTotal(val int32) {
	s.Total = val
}

// SetItems sets the value of Items.
func (s *ListContentGenerationTasksResponse) SetItems(val []ContentGenerationTask) {
	s.Items = val
}

// NewOptAudioURL returns new OptAudioURL with value set to v.
func NewOptAudioURL(v AudioURL) OptAudioURL {
	return OptAudioURL{
		Value: v,
		Set:   true,
	}
}

// OptAudioURL is optional AudioURL.
type OptAudioURL struct {
	Value AudioURL
	Set   bool
}

// IsSet returns true if OptAudioURL was set.
func (o OptAudioURL) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAudioURL) Reset() {
	var v AudioURL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAudioURL) SetTo(v AudioURL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAudioURL) Get() (v AudioURL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAudioURL) Or(d AudioURL) AudioURL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDraftTask returns new OptDraftTask with value set to v.
func NewOptDraftTask(v DraftTask) OptDraftTask {
	return OptDraftTask{
		Value: v,
		Set:   true,
	}
}

// OptDraftTask is optional DraftTask.
type OptDraftTask struct {
	Value DraftTask
	Set   bool
}

// IsSet returns true if OptDraftTask was set.
func (o OptDraftTask) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDraftTask) Reset() {
	var v DraftTask
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDraftTask) SetTo(v DraftTask) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDraftTask) Get() (v DraftTask, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDraftTask) Or(d DraftTask) DraftTask {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptImageURL returns new OptImageURL with value set to v.
func NewOptImageURL(v ImageURL) OptImageURL {
	return OptImageURL{
		Value: v,
		Set:   true,
	}
}

// OptImageURL is optional ImageURL.
type OptImageURL struct {
	Value ImageURL
	Set   bool
}

// IsSet returns true if OptImageURL was set.
func (o OptImageURL) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptImageURL) Reset() {
	var v ImageURL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptImageURL) SetTo(v ImageURL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptImageURL) Get() (v ImageURL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptImageURL) Or(d ImageURL) ImageURL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReasoningEffort returns new OptReasoningEffort with value set to v.
func NewOptReasoningEffort(v ReasoningEffort) OptReasoningEffort {
	return OptReasoningEffort{
		Value: v,
		Set:   true,
	}
}

// OptReasoningEffort is optional ReasoningEffort.
type OptReasoningEffort struct {
	Value ReasoningEffort
	Set   bool
}

// IsSet returns true if OptReasoningEffort was set.
func (o OptReasoningEffort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReasoningEffort) Reset() {
	var v ReasoningEffort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReasoningEffort) SetTo(v ReasoningEffort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReasoningEffort) Get() (v ReasoningEffort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReasoningEffort) Or(d ReasoningEffort) ReasoningEffort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTaskContent returns new OptTaskContent with value set to v.
func NewOptTaskContent(v TaskContent) OptTaskContent {
	return OptTaskContent{
		Value: v,
		Set:   true,
	}
}

// OptTaskContent is optional TaskContent.
type OptTaskContent struct {
	Value TaskContent
	Set   bool
}

// IsSet returns true if OptTaskContent was set.
func (o OptTaskContent) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTaskContent) Reset() {
	var v TaskContent
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTaskContent) SetTo(v TaskContent) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTaskContent) Get() (v TaskContent, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTaskContent) Or(d TaskContent) TaskContent {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTaskError returns new OptTaskError with value set to v.
func NewOptTaskError(v TaskError) OptTaskError {
	return OptTaskError{
		Value: v,
		Set:   true,
	}
}

// OptTaskError is optional TaskError.
type OptTaskError struct {
	Value TaskError
	Set   bool
}

// IsSet returns true if OptTaskError was set.
func (o OptTaskError) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTaskError) Reset() {
	var v TaskError
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTaskError) SetTo(v TaskError) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTaskError) Get() (v TaskError, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTaskError) Or(d TaskError) TaskError {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTaskStatus returns new OptTaskStatus with value set to v.
func NewOptTaskStatus(v TaskStatus) OptTaskStatus {
	return OptTaskStatus{
		Value: v,
		Set:   true,
	}
}

// OptTaskStatus is optional TaskStatus.
type OptTaskStatus struct {
	Value TaskStatus
	Set   bool
}

// IsSet returns true if OptTaskStatus was set.
func (o OptTaskStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTaskStatus) Reset() {
	var v TaskStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTaskStatus) SetTo(v TaskStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTaskStatus) Get() (v TaskStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTaskStatus) Or(d TaskStatus) TaskStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTaskUsage returns new OptTaskUsage with value set to v.
func NewOptTaskUsage(v TaskUsage) OptTaskUsage {
	return OptTaskUsage{
		Value: v,
		Set:   true,
	}
}

// OptTaskUsage is optional TaskUsage.
type OptTaskUsage struct {
	Value TaskUsage
	Set   bool
}

// IsSet returns true if OptTaskUsage was set.
func (o OptTaskUsage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTaskUsage) Reset() {
	var v TaskUsage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTaskUsage) SetTo(v TaskUsage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTaskUsage) Get() (v TaskUsage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTaskUsage) Or(d TaskUsage) TaskUsage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptToolUsage returns new OptToolUsage with value set to v.
func NewOptToolUsage(v ToolUsage) OptToolUsage {
	return OptToolUsage{
		Value: v,
		Set:   true,
	}
}

// OptToolUsage is optional ToolUsage.
type OptToolUsage struct {
	Value ToolUsage
	Set   bool
}

// IsSet returns true if OptToolUsage was set.
func (o OptToolUsage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptToolUsage) Reset() {
	var v ToolUsage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptToolUsage) SetTo(v ToolUsage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptToolUsage) Get() (v ToolUsage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptToolUsage) Or(d ToolUsage) ToolUsage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptVideoURL returns new OptVideoURL with value set to v.
func NewOptVideoURL(v VideoURL) OptVideoURL {
	return OptVideoURL{
		Value: v,
		Set:   true,
	}
}

// OptVideoURL is optional VideoURL.
type OptVideoURL struct {
	Value VideoURL
	Set   bool
}

// IsSet returns true if OptVideoURL was set.
func (o OptVideoURL) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptVideoURL) Reset() {
	var v VideoURL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptVideoURL) SetTo(v VideoURL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptVideoURL) Get() (v VideoURL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptVideoURL) Or(d VideoURL) VideoURL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ReasoningEffort
type ReasoningEffort string

const (
	ReasoningEffortLow    ReasoningEffort = "low"
	ReasoningEffortMedium ReasoningEffort = "medium"
	ReasoningEffortHigh   ReasoningEffort = "high"
	ReasoningEffortMax    ReasoningEffort = "max"
)

// AllValues returns all ReasoningEffort values.
func (ReasoningEffort) AllValues() []ReasoningEffort {
	return []ReasoningEffort{
		ReasoningEffortLow,
		ReasoningEffortMedium,
		ReasoningEffortHigh,
		ReasoningEffortMax,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReasoningEffort) MarshalText() ([]byte, error) {
	switch s {
	case ReasoningEffortLow:
		return []byte(s), nil
	case ReasoningEffortMedium:
		return []byte(s), nil
	case ReasoningEffortHigh:
		return []byte(s), nil
	case ReasoningEffortMax:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReasoningEffort) UnmarshalText(data []byte) error {
	switch ReasoningEffort(data) {
	case ReasoningEffortLow:
		*s = ReasoningEffortLow
		return nil
	case ReasoningEffortMedium:
		*s = ReasoningEffortMedium
		return nil
	case ReasoningEffortHigh:
		*s = ReasoningEffortHigh
		return nil
	case ReasoningEffortMax:
		*s = ReasoningEffortMax
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Generated artifact references attached to a finished task.
// Ref: #/components/schemas/TaskContent
type TaskContent struct {
	// URL of the generated video.
	VideoURL OptString `json:"video_url"`
	// URL of a generated non-video file (e.g. 3D mesh).
	FileURL OptString `json:"file_url"`
	// URL of the last-frame image, when `return_last_frame` was requested.
	LastFrameURL OptString `json:"last_frame_url"`
}

// GetVideoURL returns the value of VideoURL.
func (s *TaskContent) GetVideoURL() OptString {
	return s.VideoURL
}

// GetFileURL returns the value of FileURL.
func (s *TaskContent) GetFileURL() OptString {
	return s.FileURL
}

// GetLastFrameURL returns the value of LastFrameURL.
func (s *TaskContent) GetLastFrameURL() OptString {
	return s.LastFrameURL
}

// SetVideoURL sets the value of VideoURL.
func (s *TaskContent) SetVideoURL(val OptString) {
	s.VideoURL = val
}

// SetFileURL sets the value of FileURL.
func (s *TaskContent) SetFileURL(val OptString) {
	s.FileURL = val
}

// SetLastFrameURL sets the value of LastFrameURL.
func (s *TaskContent) SetLastFrameURL(val OptString) {
	s.LastFrameURL = val
}

// Ref: #/components/schemas/TaskError
type TaskError struct {
	// Machine-readable error code.
	Code string `json:"code"`
	// Human-readable error message.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *TaskError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *TaskError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *TaskError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *TaskError) SetMessage(val string) {
	s.Message = val
}

// Lifecycle state of a content-generation task.
// Ref: #/components/schemas/TaskStatus
type TaskStatus string

const (
	TaskStatusQueued    TaskStatus = "queued"
	TaskStatusRunning   TaskStatus = "running"
	TaskStatusCancelled TaskStatus = "cancelled"
	TaskStatusSucceeded TaskStatus = "succeeded"
	TaskStatusFailed    TaskStatus = "failed"
)

// AllValues returns all TaskStatus values.
func (TaskStatus) AllValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusQueued,
		TaskStatusRunning,
		TaskStatusCancelled,
		TaskStatusSucceeded,
		TaskStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TaskStatus) MarshalText() ([]byte, error) {
	switch s {
	case TaskStatusQueued:
		return []byte(s), nil
	case TaskStatusRunning:
		return []byte(s), nil
	case TaskStatusCancelled:
		return []byte(s), nil
	case TaskStatusSucceeded:
		return []byte(s), nil
	case TaskStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TaskStatus) UnmarshalText(data []byte) error {
	switch TaskStatus(data) {
	case TaskStatusQueued:
		*s = TaskStatusQueued
		return nil
	case TaskStatusRunning:
		*s = TaskStatusRunning
		return nil
	case TaskStatusCancelled:
		*s = TaskStatusCancelled
		return nil
	case TaskStatusSucceeded:
		*s = TaskStatusSucceeded
		return nil
	case TaskStatusFailed:
		*s = TaskStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/TaskUsage
type TaskUsage struct {
	// Tokens consumed by the completion.
	CompletionTokens int64 `json:"completion_tokens"`
	// Total tokens consumed by the request.
	TotalTokens int64 `json:"total_tokens"`
	// Per-tool usage breakdown.
	ToolUsage OptToolUsage `json:"tool_usage"`
}

// GetCompletionTokens returns the value of CompletionTokens.
func (s *TaskUsage) GetCompletionTokens() int64 {
	return s.CompletionTokens
}

// GetTotalTokens returns the value of TotalTokens.
func (s *TaskUsage) GetTotalTokens() int64 {
	return s.TotalTokens
}

// GetToolUsage returns the value of ToolUsage.
func (s *TaskUsage) GetToolUsage() OptToolUsage {
	return s.ToolUsage
}

// SetCompletionTokens sets the value of CompletionTokens.
func (s *TaskUsage) SetCompletionTokens(val int64) {
	s.CompletionTokens = val
}

// SetTotalTokens sets the value of TotalTokens.
func (s *TaskUsage) SetTotalTokens(val int64) {
	s.TotalTokens = val
}

// SetToolUsage sets the value of ToolUsage.
func (s *TaskUsage) SetToolUsage(val OptToolUsage) {
	s.ToolUsage = val
}

// Ref: #/components/schemas/Tool
type Tool struct {
	// Tool identifier. Currently only `web_search` is supported.
	Type ToolType `json:"type"`
}

// GetType returns the value of Type.
func (s *Tool) GetType() ToolType {
	return s.Type
}

// SetType sets the value of Type.
func (s *Tool) SetType(val ToolType) {
	s.Type = val
}

// Ref: #/components/schemas/ToolType
type ToolType string

const (
	ToolTypeWebSearch ToolType = "web_search"
)

// AllValues returns all ToolType values.
func (ToolType) AllValues() []ToolType {
	return []ToolType{
		ToolTypeWebSearch,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ToolType) MarshalText() ([]byte, error) {
	switch s {
	case ToolTypeWebSearch:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ToolType) UnmarshalText(data []byte) error {
	switch ToolType(data) {
	case ToolTypeWebSearch:
		*s = ToolTypeWebSearch
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ToolUsage
type ToolUsage struct {
	// Number of web-search invocations consumed.
	WebSearch OptInt64 `json:"web_search"`
}

// GetWebSearch returns the value of WebSearch.
func (s *ToolUsage) GetWebSearch() OptInt64 {
	return s.WebSearch
}

// SetWebSearch sets the value of WebSearch.
func (s *ToolUsage) SetWebSearch(val OptInt64) {
	s.WebSearch = val
}

// Ref: #/components/schemas/VideoURL
type VideoURL struct {
	// URL of the video asset.
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s *VideoURL) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *VideoURL) SetURL(val string) {
	s.URL = val
}
