// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package embedding

import (
	"github.com/go-faster/errors"
)

// An embedding vector returned by the API. The shape depends on the
// request's `encoding_format`: a list of floats when `float`, or a
// base64-encoded string when `base64`.
// Ref: #/components/schemas/Embedding
// Embedding represents sum type.
type Embedding struct {
	Type         EmbeddingType // switch on this field
	Float64Array []float64
	String       string
}

// EmbeddingType is oneOf type of Embedding.
type EmbeddingType string

// Possible values for EmbeddingType.
const (
	Float64ArrayEmbedding EmbeddingType = "[]float64"
	StringEmbedding       EmbeddingType = "string"
)

// IsFloat64Array reports whether Embedding is []float64.
func (s Embedding) IsFloat64Array() bool { return s.Type == Float64ArrayEmbedding }

// IsString reports whether Embedding is string.
func (s Embedding) IsString() bool { return s.Type == StringEmbedding }

// SetFloat64Array sets Embedding to []float64.
func (s *Embedding) SetFloat64Array(v []float64) {
	s.Type = Float64ArrayEmbedding
	s.Float64Array = v
}

// GetFloat64Array returns []float64 and true boolean if Embedding is []float64.
func (s Embedding) GetFloat64Array() (v []float64, ok bool) {
	if !s.IsFloat64Array() {
		return v, false
	}
	return s.Float64Array, true
}

// NewFloat64ArrayEmbedding returns new Embedding from []float64.
func NewFloat64ArrayEmbedding(v []float64) Embedding {
	var s Embedding
	s.SetFloat64Array(v)
	return s
}

// SetString sets Embedding to string.
func (s *Embedding) SetString(v string) {
	s.Type = StringEmbedding
	s.String = v
}

// GetString returns string and true boolean if Embedding is string.
func (s Embedding) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringEmbedding returns new Embedding from string.
func NewStringEmbedding(v string) Embedding {
	var s Embedding
	s.SetString(v)
	return s
}

// Input text(s) to embed. A single string embeds one input; an array of
// strings embeds each element independently. Each string is limited to
// 100,000 bytes and arrays to 256 items.
// Ref: #/components/schemas/EmbeddingInput
// EmbeddingInput represents sum type.
type EmbeddingInput struct {
	Type        EmbeddingInputType // switch on this field
	String      string
	StringArray []string
}

// EmbeddingInputType is oneOf type of EmbeddingInput.
type EmbeddingInputType string

// Possible values for EmbeddingInputType.
const (
	StringEmbeddingInput      EmbeddingInputType = "string"
	StringArrayEmbeddingInput EmbeddingInputType = "[]string"
)

// IsString reports whether EmbeddingInput is string.
func (s EmbeddingInput) IsString() bool { return s.Type == StringEmbeddingInput }

// IsStringArray reports whether EmbeddingInput is []string.
func (s EmbeddingInput) IsStringArray() bool { return s.Type == StringArrayEmbeddingInput }

// SetString sets EmbeddingInput to string.
func (s *EmbeddingInput) SetString(v string) {
	s.Type = StringEmbeddingInput
	s.String = v
}

// GetString returns string and true boolean if EmbeddingInput is string.
func (s EmbeddingInput) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringEmbeddingInput returns new EmbeddingInput from string.
func NewStringEmbeddingInput(v string) EmbeddingInput {
	var s EmbeddingInput
	s.SetString(v)
	return s
}

// SetStringArray sets EmbeddingInput to []string.
func (s *EmbeddingInput) SetStringArray(v []string) {
	s.Type = StringArrayEmbeddingInput
	s.StringArray = v
}

// GetStringArray returns []string and true boolean if EmbeddingInput is []string.
func (s EmbeddingInput) GetStringArray() (v []string, ok bool) {
	if !s.IsStringArray() {
		return v, false
	}
	return s.StringArray, true
}

// NewStringArrayEmbeddingInput returns new EmbeddingInput from []string.
func NewStringArrayEmbeddingInput(v []string) EmbeddingInput {
	var s EmbeddingInput
	s.SetStringArray(v)
	return s
}

// A single embedding produced for one input.
// Ref: #/components/schemas/EmbeddingItem
type EmbeddingItem struct {
	// The embedding vector.
	Embedding Embedding `json:"embedding"`
	// The index of this embedding in the request `input` array.
	Index int32 `json:"index"`
	// The object type. Always `embedding`.
	Object EmbeddingItemObject `json:"object"`
}

// GetEmbedding returns the value of Embedding.
func (s *EmbeddingItem) GetEmbedding() Embedding {
	return s.Embedding
}

// GetIndex returns the value of Index.
func (s *EmbeddingItem) GetIndex() int32 {
	return s.Index
}

// GetObject returns the value of Object.
func (s *EmbeddingItem) GetObject() EmbeddingItemObject {
	return s.Object
}

// SetEmbedding sets the value of Embedding.
func (s *EmbeddingItem) SetEmbedding(val Embedding) {
	s.Embedding = val
}

// SetIndex sets the value of Index.
func (s *EmbeddingItem) SetIndex(val int32) {
	s.Index = val
}

// SetObject sets the value of Object.
func (s *EmbeddingItem) SetObject(val EmbeddingItemObject) {
	s.Object = val
}

// The object type. Always `embedding`.
type EmbeddingItemObject string

const (
	EmbeddingItemObjectEmbedding EmbeddingItemObject = "embedding"
)

// AllValues returns all EmbeddingItemObject values.
func (EmbeddingItemObject) AllValues() []EmbeddingItemObject {
	return []EmbeddingItemObject{
		EmbeddingItemObjectEmbedding,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EmbeddingItemObject) MarshalText() ([]byte, error) {
	switch s {
	case EmbeddingItemObjectEmbedding:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EmbeddingItemObject) UnmarshalText(data []byte) error {
	switch EmbeddingItemObject(data) {
	case EmbeddingItemObjectEmbedding:
		*s = EmbeddingItemObjectEmbedding
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/EmbeddingRequest
type EmbeddingRequest struct {
	// Endpoint ID of the model to use.
	Model string `json:"model"`
	// Input text to embed, as a string or array of strings. To embed
	// multiple inputs in one request, pass an array.
	Input EmbeddingInput `json:"input"`
	// The format embeddings are returned in. Defaults to `float`.
	EncodingFormat OptEncodingFormat `json:"encoding_format"`
	// Override the embedding dimensionality.
	Dimensions OptInt64 `json:"dimensions"`
	// A unique identifier representing the end-user, which can help the
	// service monitor and detect abuse.
	User OptString `json:"user"`
}

// GetModel returns the value of Model.
func (s *EmbeddingRequest) GetModel() string {
	return s.Model
}

// GetInput returns the value of Input.
func (s *EmbeddingRequest) GetInput() EmbeddingInput {
	return s.Input
}

// GetEncodingFormat returns the value of EncodingFormat.
func (s *EmbeddingRequest) GetEncodingFormat() OptEncodingFormat {
	return s.EncodingFormat
}

// GetDimensions returns the value of Dimensions.
func (s *EmbeddingRequest) GetDimensions() OptInt64 {
	return s.Dimensions
}

// GetUser returns the value of User.
func (s *EmbeddingRequest) GetUser() OptString {
	return s.User
}

// SetModel sets the value of Model.
func (s *EmbeddingRequest) SetModel(val string) {
	s.Model = val
}

// SetInput sets the value of Input.
func (s *EmbeddingRequest) SetInput(val EmbeddingInput) {
	s.Input = val
}

// SetEncodingFormat sets the value of EncodingFormat.
func (s *EmbeddingRequest) SetEncodingFormat(val OptEncodingFormat) {
	s.EncodingFormat = val
}

// SetDimensions sets the value of Dimensions.
func (s *EmbeddingRequest) SetDimensions(val OptInt64) {
	s.Dimensions = val
}

// SetUser sets the value of User.
func (s *EmbeddingRequest) SetUser(val OptString) {
	s.User = val
}

// Ref: #/components/schemas/EmbeddingResponse
type EmbeddingResponse struct {
	// A unique identifier for the embedding response.
	ID string `json:"id"`
	// The object type. Always `list`.
	Object EmbeddingResponseObject `json:"object"`
	// Unix timestamp (in seconds) of when the response was created.
	Created int64 `json:"created"`
	// The model that produced the embeddings.
	Model string `json:"model"`
	// The list of embeddings, one per input.
	Data []EmbeddingItem `json:"data"`
	// Token usage information for the request.
	Usage EmbeddingUsage `json:"usage"`
}

// GetID returns the value of ID.
func (s *EmbeddingResponse) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *EmbeddingResponse) GetObject() EmbeddingResponseObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *EmbeddingResponse) GetCreated() int64 {
	return s.Created
}

// GetModel returns the value of Model.
func (s *EmbeddingResponse) GetModel() string {
	return s.Model
}

// GetData returns the value of Data.
func (s *EmbeddingResponse) GetData() []EmbeddingItem {
	return s.Data
}

// GetUsage returns the value of Usage.
func (s *EmbeddingResponse) GetUsage() EmbeddingUsage {
	return s.Usage
}

// SetID sets the value of ID.
func (s *EmbeddingResponse) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *EmbeddingResponse) SetObject(val EmbeddingResponseObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *EmbeddingResponse) SetCreated(val int64) {
	s.Created = val
}

// SetModel sets the value of Model.
func (s *EmbeddingResponse) SetModel(val string) {
	s.Model = val
}

// SetData sets the value of Data.
func (s *EmbeddingResponse) SetData(val []EmbeddingItem) {
	s.Data = val
}

// SetUsage sets the value of Usage.
func (s *EmbeddingResponse) SetUsage(val EmbeddingUsage) {
	s.Usage = val
}

// The object type. Always `list`.
type EmbeddingResponseObject string

const (
	EmbeddingResponseObjectList EmbeddingResponseObject = "list"
)

// AllValues returns all EmbeddingResponseObject values.
func (EmbeddingResponseObject) AllValues() []EmbeddingResponseObject {
	return []EmbeddingResponseObject{
		EmbeddingResponseObjectList,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EmbeddingResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case EmbeddingResponseObjectList:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EmbeddingResponseObject) UnmarshalText(data []byte) error {
	switch EmbeddingResponseObject(data) {
	case EmbeddingResponseObjectList:
		*s = EmbeddingResponseObjectList
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Token usage information for an embedding request.
// Ref: #/components/schemas/EmbeddingUsage
type EmbeddingUsage struct {
	// The number of tokens consumed by the prompt.
	PromptTokens int64 `json:"prompt_tokens"`
	// The total number of tokens used by the request.
	TotalTokens int64 `json:"total_tokens"`
}

// GetPromptTokens returns the value of PromptTokens.
func (s *EmbeddingUsage) GetPromptTokens() int64 {
	return s.PromptTokens
}

// GetTotalTokens returns the value of TotalTokens.
func (s *EmbeddingUsage) GetTotalTokens() int64 {
	return s.TotalTokens
}

// SetPromptTokens sets the value of PromptTokens.
func (s *EmbeddingUsage) SetPromptTokens(val int64) {
	s.PromptTokens = val
}

// SetTotalTokens sets the value of TotalTokens.
func (s *EmbeddingUsage) SetTotalTokens(val int64) {
	s.TotalTokens = val
}

// Ref: #/components/schemas/EncodingFormat
type EncodingFormat string

const (
	EncodingFormatFloat  EncodingFormat = "float"
	EncodingFormatBase64 EncodingFormat = "base64"
)

// AllValues returns all EncodingFormat values.
func (EncodingFormat) AllValues() []EncodingFormat {
	return []EncodingFormat{
		EncodingFormatFloat,
		EncodingFormatBase64,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EncodingFormat) MarshalText() ([]byte, error) {
	switch s {
	case EncodingFormatFloat:
		return []byte(s), nil
	case EncodingFormatBase64:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EncodingFormat) UnmarshalText(data []byte) error {
	switch EncodingFormat(data) {
	case EncodingFormatFloat:
		*s = EncodingFormatFloat
		return nil
	case EncodingFormatBase64:
		*s = EncodingFormatBase64
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptEncodingFormat returns new OptEncodingFormat with value set to v.
func NewOptEncodingFormat(v EncodingFormat) OptEncodingFormat {
	return OptEncodingFormat{
		Value: v,
		Set:   true,
	}
}

// OptEncodingFormat is optional EncodingFormat.
type OptEncodingFormat struct {
	Value EncodingFormat
	Set   bool
}

// IsSet returns true if OptEncodingFormat was set.
func (o OptEncodingFormat) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEncodingFormat) Reset() {
	var v EncodingFormat
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEncodingFormat) SetTo(v EncodingFormat) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEncodingFormat) Get() (v EncodingFormat, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEncodingFormat) Or(d EncodingFormat) EncodingFormat {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
