// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package skill

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/CreateSkillRequest
type CreateSkillRequest struct {
	// Skill 展示名。.
	DisplayTitle OptString `json:"display_title" form:"display_title"`
}

// GetDisplayTitle returns the value of DisplayTitle.
func (s *CreateSkillRequest) GetDisplayTitle() OptString {
	return s.DisplayTitle
}

// SetDisplayTitle sets the value of DisplayTitle.
func (s *CreateSkillRequest) SetDisplayTitle(val OptString) {
	s.DisplayTitle = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// 用户上传到 Managed Agents 控制面的技能摘要。
// 与其他资源不同：Skill 用 `object` 而不是 `type` 作为对象类型判别字段，
// 且 `created_at` 是 Unix 秒（int64）而非 RFC 3339 字符串 —— 与
// ark-managed-agents thrift 契约保持一致。.
// Ref: #/components/schemas/Skill
type Skill struct {
	// Skill ID，形如 `skill_01XJ5...`。.
	ID string `json:"id"`
	// 固定 `"skill"`。.
	Object SkillObject `json:"object"`
	// 创建时间（Unix 秒）。.
	CreatedAt int64 `json:"created_at"`
	// 描述信息。.
	Description OptString `json:"description"`
	// 最新版本号。.
	LatestVersion string `json:"latest_version"`
	// 人类可读名称。.
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *Skill) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *Skill) GetObject() SkillObject {
	return s.Object
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Skill) GetCreatedAt() int64 {
	return s.CreatedAt
}

// GetDescription returns the value of Description.
func (s *Skill) GetDescription() OptString {
	return s.Description
}

// GetLatestVersion returns the value of LatestVersion.
func (s *Skill) GetLatestVersion() string {
	return s.LatestVersion
}

// GetName returns the value of Name.
func (s *Skill) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Skill) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *Skill) SetObject(val SkillObject) {
	s.Object = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Skill) SetCreatedAt(val int64) {
	s.CreatedAt = val
}

// SetDescription sets the value of Description.
func (s *Skill) SetDescription(val OptString) {
	s.Description = val
}

// SetLatestVersion sets the value of LatestVersion.
func (s *Skill) SetLatestVersion(val string) {
	s.LatestVersion = val
}

// SetName sets the value of Name.
func (s *Skill) SetName(val string) {
	s.Name = val
}

// 固定 `"skill"`。.
type SkillObject string

const (
	SkillObjectSkill SkillObject = "skill"
)

// AllValues returns all SkillObject values.
func (SkillObject) AllValues() []SkillObject {
	return []SkillObject{
		SkillObjectSkill,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SkillObject) MarshalText() ([]byte, error) {
	switch s {
	case SkillObjectSkill:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SkillObject) UnmarshalText(data []byte) error {
	switch SkillObject(data) {
	case SkillObjectSkill:
		*s = SkillObjectSkill
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
