// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Code generated by ogen, DO NOT EDIT.

package images

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/CreateImageGenerationRequest
type CreateImageGenerationRequest struct {
	// The model identifier to use.
	Model string `json:"model"`
	// Text prompt describing the desired image.
	Prompt string `json:"prompt"`
	// Reference / edit images. Each entry is a URL or a `data:` URI.
	Image []string `json:"image"`
	// Stream partial images as they are generated (server-sent events).
	Stream OptBool `json:"stream"`
	// How generated image bytes are returned. Defaults to `url`.
	ResponseFormat OptResponseFormat `json:"response_format"`
	// Random seed for reproducible generation.
	Seed OptInt64 `json:"seed"`
	// Classifier-free guidance scale for the text prompt.
	GuidanceScale OptFloat64 `json:"guidance_scale"`
	// Classifier-free guidance scale for reference images (edit / R2I).
	ImageGuidanceScale OptFloat64 `json:"image_guidance_scale"`
	// Output size hint (e.g. `1024x1024`, `2K`, `adaptive`).
	Size OptString `json:"size"`
	// Embed a watermark in the generated image.
	Watermark OptBool `json:"watermark"`
	// Multi-image generation mode.
	SequentialImageGeneration OptSequentialImageGenerationMode `json:"sequential_image_generation"`
	// Tuning for `sequential_image_generation`.
	SequentialImageGenerationOptions OptSequentialImageGenerationOptions `json:"sequential_image_generation_options"`
	// Run the prompt-optimization pass before generation.
	OptimizePrompt OptBool `json:"optimize_prompt"`
	// Tuning for `optimize_prompt`.
	OptimizePromptOptions OptOptimizePromptOptions `json:"optimize_prompt_options"`
	// Tools the model may invoke during generation.
	Tools []Tool `json:"tools"`
	// Container/codec for the generated image bytes.
	OutputFormat OptOutputFormat `json:"output_format"`
}

// GetModel returns the value of Model.
func (s *CreateImageGenerationRequest) GetModel() string {
	return s.Model
}

// GetPrompt returns the value of Prompt.
func (s *CreateImageGenerationRequest) GetPrompt() string {
	return s.Prompt
}

// GetImage returns the value of Image.
func (s *CreateImageGenerationRequest) GetImage() []string {
	return s.Image
}

// GetStream returns the value of Stream.
func (s *CreateImageGenerationRequest) GetStream() OptBool {
	return s.Stream
}

// GetResponseFormat returns the value of ResponseFormat.
func (s *CreateImageGenerationRequest) GetResponseFormat() OptResponseFormat {
	return s.ResponseFormat
}

// GetSeed returns the value of Seed.
func (s *CreateImageGenerationRequest) GetSeed() OptInt64 {
	return s.Seed
}

// GetGuidanceScale returns the value of GuidanceScale.
func (s *CreateImageGenerationRequest) GetGuidanceScale() OptFloat64 {
	return s.GuidanceScale
}

// GetImageGuidanceScale returns the value of ImageGuidanceScale.
func (s *CreateImageGenerationRequest) GetImageGuidanceScale() OptFloat64 {
	return s.ImageGuidanceScale
}

// GetSize returns the value of Size.
func (s *CreateImageGenerationRequest) GetSize() OptString {
	return s.Size
}

// GetWatermark returns the value of Watermark.
func (s *CreateImageGenerationRequest) GetWatermark() OptBool {
	return s.Watermark
}

// GetSequentialImageGeneration returns the value of SequentialImageGeneration.
func (s *CreateImageGenerationRequest) GetSequentialImageGeneration() OptSequentialImageGenerationMode {
	return s.SequentialImageGeneration
}

// GetSequentialImageGenerationOptions returns the value of SequentialImageGenerationOptions.
func (s *CreateImageGenerationRequest) GetSequentialImageGenerationOptions() OptSequentialImageGenerationOptions {
	return s.SequentialImageGenerationOptions
}

// GetOptimizePrompt returns the value of OptimizePrompt.
func (s *CreateImageGenerationRequest) GetOptimizePrompt() OptBool {
	return s.OptimizePrompt
}

// GetOptimizePromptOptions returns the value of OptimizePromptOptions.
func (s *CreateImageGenerationRequest) GetOptimizePromptOptions() OptOptimizePromptOptions {
	return s.OptimizePromptOptions
}

// GetTools returns the value of Tools.
func (s *CreateImageGenerationRequest) GetTools() []Tool {
	return s.Tools
}

// GetOutputFormat returns the value of OutputFormat.
func (s *CreateImageGenerationRequest) GetOutputFormat() OptOutputFormat {
	return s.OutputFormat
}

// SetModel sets the value of Model.
func (s *CreateImageGenerationRequest) SetModel(val string) {
	s.Model = val
}

// SetPrompt sets the value of Prompt.
func (s *CreateImageGenerationRequest) SetPrompt(val string) {
	s.Prompt = val
}

// SetImage sets the value of Image.
func (s *CreateImageGenerationRequest) SetImage(val []string) {
	s.Image = val
}

// SetStream sets the value of Stream.
func (s *CreateImageGenerationRequest) SetStream(val OptBool) {
	s.Stream = val
}

// SetResponseFormat sets the value of ResponseFormat.
func (s *CreateImageGenerationRequest) SetResponseFormat(val OptResponseFormat) {
	s.ResponseFormat = val
}

// SetSeed sets the value of Seed.
func (s *CreateImageGenerationRequest) SetSeed(val OptInt64) {
	s.Seed = val
}

// SetGuidanceScale sets the value of GuidanceScale.
func (s *CreateImageGenerationRequest) SetGuidanceScale(val OptFloat64) {
	s.GuidanceScale = val
}

// SetImageGuidanceScale sets the value of ImageGuidanceScale.
func (s *CreateImageGenerationRequest) SetImageGuidanceScale(val OptFloat64) {
	s.ImageGuidanceScale = val
}

// SetSize sets the value of Size.
func (s *CreateImageGenerationRequest) SetSize(val OptString) {
	s.Size = val
}

// SetWatermark sets the value of Watermark.
func (s *CreateImageGenerationRequest) SetWatermark(val OptBool) {
	s.Watermark = val
}

// SetSequentialImageGeneration sets the value of SequentialImageGeneration.
func (s *CreateImageGenerationRequest) SetSequentialImageGeneration(val OptSequentialImageGenerationMode) {
	s.SequentialImageGeneration = val
}

// SetSequentialImageGenerationOptions sets the value of SequentialImageGenerationOptions.
func (s *CreateImageGenerationRequest) SetSequentialImageGenerationOptions(val OptSequentialImageGenerationOptions) {
	s.SequentialImageGenerationOptions = val
}

// SetOptimizePrompt sets the value of OptimizePrompt.
func (s *CreateImageGenerationRequest) SetOptimizePrompt(val OptBool) {
	s.OptimizePrompt = val
}

// SetOptimizePromptOptions sets the value of OptimizePromptOptions.
func (s *CreateImageGenerationRequest) SetOptimizePromptOptions(val OptOptimizePromptOptions) {
	s.OptimizePromptOptions = val
}

// SetTools sets the value of Tools.
func (s *CreateImageGenerationRequest) SetTools(val []Tool) {
	s.Tools = val
}

// SetOutputFormat sets the value of OutputFormat.
func (s *CreateImageGenerationRequest) SetOutputFormat(val OptOutputFormat) {
	s.OutputFormat = val
}

// One generated image. Exactly one of `url` / `b64_json` is set, depending on the request
// `response_format`.
// Ref: #/components/schemas/ImageDataItem
type ImageDataItem struct {
	// URL of the generated image. Set when `response_format=url`.
	URL OptString `json:"url"`
	// Base64-encoded image bytes. Set when `response_format=b64_json`.
	B64JSON OptString `json:"b64_json"`
	// Resolved output size for this image (e.g. `1024x1024`).
	Size OptString `json:"size"`
	// Per-image failure (set when this slot failed while others succeeded).
	Error OptImageError `json:"error"`
}

// GetURL returns the value of URL.
func (s *ImageDataItem) GetURL() OptString {
	return s.URL
}

// GetB64JSON returns the value of B64JSON.
func (s *ImageDataItem) GetB64JSON() OptString {
	return s.B64JSON
}

// GetSize returns the value of Size.
func (s *ImageDataItem) GetSize() OptString {
	return s.Size
}

// GetError returns the value of Error.
func (s *ImageDataItem) GetError() OptImageError {
	return s.Error
}

// SetURL sets the value of URL.
func (s *ImageDataItem) SetURL(val OptString) {
	s.URL = val
}

// SetB64JSON sets the value of B64JSON.
func (s *ImageDataItem) SetB64JSON(val OptString) {
	s.B64JSON = val
}

// SetSize sets the value of Size.
func (s *ImageDataItem) SetSize(val OptString) {
	s.Size = val
}

// SetError sets the value of Error.
func (s *ImageDataItem) SetError(val OptImageError) {
	s.Error = val
}

// Ref: #/components/schemas/ImageError
type ImageError struct {
	// Machine-readable error code.
	Code string `json:"code"`
	// Human-readable error message.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ImageError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ImageError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ImageError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ImageError) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/ImageGenerationResponse
type ImageGenerationResponse struct {
	// Model that produced the result.
	Model string `json:"model"`
	// Unix timestamp (seconds) when the response was produced.
	Created int64 `json:"created"`
	// Generated images. Empty when the request failed entirely.
	Data []ImageDataItem `json:"data"`
	// Tools that were invoked.
	Tools []Tool `json:"tools"`
	// Token / image usage.
	Usage OptUsage `json:"usage"`
	// Top-level failure (set when no images could be produced).
	Error OptImageError `json:"error"`
}

// GetModel returns the value of Model.
func (s *ImageGenerationResponse) GetModel() string {
	return s.Model
}

// GetCreated returns the value of Created.
func (s *ImageGenerationResponse) GetCreated() int64 {
	return s.Created
}

// GetData returns the value of Data.
func (s *ImageGenerationResponse) GetData() []ImageDataItem {
	return s.Data
}

// GetTools returns the value of Tools.
func (s *ImageGenerationResponse) GetTools() []Tool {
	return s.Tools
}

// GetUsage returns the value of Usage.
func (s *ImageGenerationResponse) GetUsage() OptUsage {
	return s.Usage
}

// GetError returns the value of Error.
func (s *ImageGenerationResponse) GetError() OptImageError {
	return s.Error
}

// SetModel sets the value of Model.
func (s *ImageGenerationResponse) SetModel(val string) {
	s.Model = val
}

// SetCreated sets the value of Created.
func (s *ImageGenerationResponse) SetCreated(val int64) {
	s.Created = val
}

// SetData sets the value of Data.
func (s *ImageGenerationResponse) SetData(val []ImageDataItem) {
	s.Data = val
}

// SetTools sets the value of Tools.
func (s *ImageGenerationResponse) SetTools(val []Tool) {
	s.Tools = val
}

// SetUsage sets the value of Usage.
func (s *ImageGenerationResponse) SetUsage(val OptUsage) {
	s.Usage = val
}

// SetError sets the value of Error.
func (s *ImageGenerationResponse) SetError(val OptImageError) {
	s.Error = val
}

func (*ImageGenerationResponse) imageGenerationsGenerateRes() {}

// One frame of the SSE response on POST /images/generations when
// `stream=true`. Wire format:
// event: <type>
// data:  <json>
// Three event types share this single struct (same shape as the legacy
// IDL); switch on `type` to decide which optional fields are populated:
// - `image_generation.partial_succeeded` → `image_index`, `url` *or*
// `b64_json`, `size`.
// - `image_generation.partial_failed`    → `image_index`, `error`.
// - `image_generation.completed`         → `tools`, `usage`. No `image_*`.
// Ref: #/components/schemas/ImageGenerationStreamEvent
type ImageGenerationStreamEvent struct {
	// Discriminator.
	Type ImageGenerationStreamEventType `json:"type"`
	// Model that produced the result.
	Model string `json:"model"`
	// Unix timestamp (seconds) when the event was produced.
	Created int64 `json:"created"`
	// 0-based index of the image this event refers to (partial_* only).
	ImageIndex OptInt32 `json:"image_index"`
	// URL of the partially-generated image (partial_succeeded, response_format=url).
	URL OptString `json:"url"`
	// Base64-encoded image bytes (partial_succeeded, response_format=b64_json).
	B64JSON OptString `json:"b64_json"`
	// Resolved size of the partial image, e.g. `1024x1024`.
	Size OptString `json:"size"`
	// Tools invoked during the stream (completed only).
	Tools []Tool `json:"tools"`
	// Token / image usage (completed only).
	Usage OptUsage `json:"usage"`
	// Per-event failure (partial_failed; also surfaces top-level failures).
	Error OptImageError `json:"error"`
}

// GetType returns the value of Type.
func (s *ImageGenerationStreamEvent) GetType() ImageGenerationStreamEventType {
	return s.Type
}

// GetModel returns the value of Model.
func (s *ImageGenerationStreamEvent) GetModel() string {
	return s.Model
}

// GetCreated returns the value of Created.
func (s *ImageGenerationStreamEvent) GetCreated() int64 {
	return s.Created
}

// GetImageIndex returns the value of ImageIndex.
func (s *ImageGenerationStreamEvent) GetImageIndex() OptInt32 {
	return s.ImageIndex
}

// GetURL returns the value of URL.
func (s *ImageGenerationStreamEvent) GetURL() OptString {
	return s.URL
}

// GetB64JSON returns the value of B64JSON.
func (s *ImageGenerationStreamEvent) GetB64JSON() OptString {
	return s.B64JSON
}

// GetSize returns the value of Size.
func (s *ImageGenerationStreamEvent) GetSize() OptString {
	return s.Size
}

// GetTools returns the value of Tools.
func (s *ImageGenerationStreamEvent) GetTools() []Tool {
	return s.Tools
}

// GetUsage returns the value of Usage.
func (s *ImageGenerationStreamEvent) GetUsage() OptUsage {
	return s.Usage
}

// GetError returns the value of Error.
func (s *ImageGenerationStreamEvent) GetError() OptImageError {
	return s.Error
}

// SetType sets the value of Type.
func (s *ImageGenerationStreamEvent) SetType(val ImageGenerationStreamEventType) {
	s.Type = val
}

// SetModel sets the value of Model.
func (s *ImageGenerationStreamEvent) SetModel(val string) {
	s.Model = val
}

// SetCreated sets the value of Created.
func (s *ImageGenerationStreamEvent) SetCreated(val int64) {
	s.Created = val
}

// SetImageIndex sets the value of ImageIndex.
func (s *ImageGenerationStreamEvent) SetImageIndex(val OptInt32) {
	s.ImageIndex = val
}

// SetURL sets the value of URL.
func (s *ImageGenerationStreamEvent) SetURL(val OptString) {
	s.URL = val
}

// SetB64JSON sets the value of B64JSON.
func (s *ImageGenerationStreamEvent) SetB64JSON(val OptString) {
	s.B64JSON = val
}

// SetSize sets the value of Size.
func (s *ImageGenerationStreamEvent) SetSize(val OptString) {
	s.Size = val
}

// SetTools sets the value of Tools.
func (s *ImageGenerationStreamEvent) SetTools(val []Tool) {
	s.Tools = val
}

// SetUsage sets the value of Usage.
func (s *ImageGenerationStreamEvent) SetUsage(val OptUsage) {
	s.Usage = val
}

// SetError sets the value of Error.
func (s *ImageGenerationStreamEvent) SetError(val OptImageError) {
	s.Error = val
}

func (*ImageGenerationStreamEvent) imageGenerationsGenerateRes() {}

// Discriminator on `ImageGenerationStreamEvent.type`.
// Ref: #/components/schemas/ImageGenerationStreamEventType
type ImageGenerationStreamEventType string

const (
	ImageGenerationStreamEventTypeImageGenerationPartialSucceeded ImageGenerationStreamEventType = "image_generation.partial_succeeded"
	ImageGenerationStreamEventTypeImageGenerationPartialFailed    ImageGenerationStreamEventType = "image_generation.partial_failed"
	ImageGenerationStreamEventTypeImageGenerationCompleted        ImageGenerationStreamEventType = "image_generation.completed"
)

// AllValues returns all ImageGenerationStreamEventType values.
func (ImageGenerationStreamEventType) AllValues() []ImageGenerationStreamEventType {
	return []ImageGenerationStreamEventType{
		ImageGenerationStreamEventTypeImageGenerationPartialSucceeded,
		ImageGenerationStreamEventTypeImageGenerationPartialFailed,
		ImageGenerationStreamEventTypeImageGenerationCompleted,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ImageGenerationStreamEventType) MarshalText() ([]byte, error) {
	switch s {
	case ImageGenerationStreamEventTypeImageGenerationPartialSucceeded:
		return []byte(s), nil
	case ImageGenerationStreamEventTypeImageGenerationPartialFailed:
		return []byte(s), nil
	case ImageGenerationStreamEventTypeImageGenerationCompleted:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ImageGenerationStreamEventType) UnmarshalText(data []byte) error {
	switch ImageGenerationStreamEventType(data) {
	case ImageGenerationStreamEventTypeImageGenerationPartialSucceeded:
		*s = ImageGenerationStreamEventTypeImageGenerationPartialSucceeded
		return nil
	case ImageGenerationStreamEventTypeImageGenerationPartialFailed:
		*s = ImageGenerationStreamEventTypeImageGenerationPartialFailed
		return nil
	case ImageGenerationStreamEventTypeImageGenerationCompleted:
		*s = ImageGenerationStreamEventTypeImageGenerationCompleted
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptImageError returns new OptImageError with value set to v.
func NewOptImageError(v ImageError) OptImageError {
	return OptImageError{
		Value: v,
		Set:   true,
	}
}

// OptImageError is optional ImageError.
type OptImageError struct {
	Value ImageError
	Set   bool
}

// IsSet returns true if OptImageError was set.
func (o OptImageError) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptImageError) Reset() {
	var v ImageError
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptImageError) SetTo(v ImageError) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptImageError) Get() (v ImageError, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptImageError) Or(d ImageError) ImageError {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOptimizePromptMode returns new OptOptimizePromptMode with value set to v.
func NewOptOptimizePromptMode(v OptimizePromptMode) OptOptimizePromptMode {
	return OptOptimizePromptMode{
		Value: v,
		Set:   true,
	}
}

// OptOptimizePromptMode is optional OptimizePromptMode.
type OptOptimizePromptMode struct {
	Value OptimizePromptMode
	Set   bool
}

// IsSet returns true if OptOptimizePromptMode was set.
func (o OptOptimizePromptMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOptimizePromptMode) Reset() {
	var v OptimizePromptMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOptimizePromptMode) SetTo(v OptimizePromptMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOptimizePromptMode) Get() (v OptimizePromptMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOptimizePromptMode) Or(d OptimizePromptMode) OptimizePromptMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOptimizePromptOptions returns new OptOptimizePromptOptions with value set to v.
func NewOptOptimizePromptOptions(v OptimizePromptOptions) OptOptimizePromptOptions {
	return OptOptimizePromptOptions{
		Value: v,
		Set:   true,
	}
}

// OptOptimizePromptOptions is optional OptimizePromptOptions.
type OptOptimizePromptOptions struct {
	Value OptimizePromptOptions
	Set   bool
}

// IsSet returns true if OptOptimizePromptOptions was set.
func (o OptOptimizePromptOptions) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOptimizePromptOptions) Reset() {
	var v OptimizePromptOptions
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOptimizePromptOptions) SetTo(v OptimizePromptOptions) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOptimizePromptOptions) Get() (v OptimizePromptOptions, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOptimizePromptOptions) Or(d OptimizePromptOptions) OptimizePromptOptions {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOptimizePromptThinking returns new OptOptimizePromptThinking with value set to v.
func NewOptOptimizePromptThinking(v OptimizePromptThinking) OptOptimizePromptThinking {
	return OptOptimizePromptThinking{
		Value: v,
		Set:   true,
	}
}

// OptOptimizePromptThinking is optional OptimizePromptThinking.
type OptOptimizePromptThinking struct {
	Value OptimizePromptThinking
	Set   bool
}

// IsSet returns true if OptOptimizePromptThinking was set.
func (o OptOptimizePromptThinking) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOptimizePromptThinking) Reset() {
	var v OptimizePromptThinking
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOptimizePromptThinking) SetTo(v OptimizePromptThinking) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOptimizePromptThinking) Get() (v OptimizePromptThinking, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOptimizePromptThinking) Or(d OptimizePromptThinking) OptimizePromptThinking {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOutputFormat returns new OptOutputFormat with value set to v.
func NewOptOutputFormat(v OutputFormat) OptOutputFormat {
	return OptOutputFormat{
		Value: v,
		Set:   true,
	}
}

// OptOutputFormat is optional OutputFormat.
type OptOutputFormat struct {
	Value OutputFormat
	Set   bool
}

// IsSet returns true if OptOutputFormat was set.
func (o OptOutputFormat) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOutputFormat) Reset() {
	var v OutputFormat
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOutputFormat) SetTo(v OutputFormat) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOutputFormat) Get() (v OutputFormat, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOutputFormat) Or(d OutputFormat) OutputFormat {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptResponseFormat returns new OptResponseFormat with value set to v.
func NewOptResponseFormat(v ResponseFormat) OptResponseFormat {
	return OptResponseFormat{
		Value: v,
		Set:   true,
	}
}

// OptResponseFormat is optional ResponseFormat.
type OptResponseFormat struct {
	Value ResponseFormat
	Set   bool
}

// IsSet returns true if OptResponseFormat was set.
func (o OptResponseFormat) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptResponseFormat) Reset() {
	var v ResponseFormat
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptResponseFormat) SetTo(v ResponseFormat) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptResponseFormat) Get() (v ResponseFormat, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptResponseFormat) Or(d ResponseFormat) ResponseFormat {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSequentialImageGenerationMode returns new OptSequentialImageGenerationMode with value set to v.
func NewOptSequentialImageGenerationMode(v SequentialImageGenerationMode) OptSequentialImageGenerationMode {
	return OptSequentialImageGenerationMode{
		Value: v,
		Set:   true,
	}
}

// OptSequentialImageGenerationMode is optional SequentialImageGenerationMode.
type OptSequentialImageGenerationMode struct {
	Value SequentialImageGenerationMode
	Set   bool
}

// IsSet returns true if OptSequentialImageGenerationMode was set.
func (o OptSequentialImageGenerationMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSequentialImageGenerationMode) Reset() {
	var v SequentialImageGenerationMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSequentialImageGenerationMode) SetTo(v SequentialImageGenerationMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSequentialImageGenerationMode) Get() (v SequentialImageGenerationMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSequentialImageGenerationMode) Or(d SequentialImageGenerationMode) SequentialImageGenerationMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSequentialImageGenerationOptions returns new OptSequentialImageGenerationOptions with value set to v.
func NewOptSequentialImageGenerationOptions(v SequentialImageGenerationOptions) OptSequentialImageGenerationOptions {
	return OptSequentialImageGenerationOptions{
		Value: v,
		Set:   true,
	}
}

// OptSequentialImageGenerationOptions is optional SequentialImageGenerationOptions.
type OptSequentialImageGenerationOptions struct {
	Value SequentialImageGenerationOptions
	Set   bool
}

// IsSet returns true if OptSequentialImageGenerationOptions was set.
func (o OptSequentialImageGenerationOptions) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSequentialImageGenerationOptions) Reset() {
	var v SequentialImageGenerationOptions
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSequentialImageGenerationOptions) SetTo(v SequentialImageGenerationOptions) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSequentialImageGenerationOptions) Get() (v SequentialImageGenerationOptions, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSequentialImageGenerationOptions) Or(d SequentialImageGenerationOptions) SequentialImageGenerationOptions {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptToolUsage returns new OptToolUsage with value set to v.
func NewOptToolUsage(v ToolUsage) OptToolUsage {
	return OptToolUsage{
		Value: v,
		Set:   true,
	}
}

// OptToolUsage is optional ToolUsage.
type OptToolUsage struct {
	Value ToolUsage
	Set   bool
}

// IsSet returns true if OptToolUsage was set.
func (o OptToolUsage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptToolUsage) Reset() {
	var v ToolUsage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptToolUsage) SetTo(v ToolUsage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptToolUsage) Get() (v ToolUsage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptToolUsage) Or(d ToolUsage) ToolUsage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUsage returns new OptUsage with value set to v.
func NewOptUsage(v Usage) OptUsage {
	return OptUsage{
		Value: v,
		Set:   true,
	}
}

// OptUsage is optional Usage.
type OptUsage struct {
	Value Usage
	Set   bool
}

// IsSet returns true if OptUsage was set.
func (o OptUsage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUsage) Reset() {
	var v Usage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUsage) SetTo(v Usage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUsage) Get() (v Usage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUsage) Or(d Usage) Usage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Prompt-optimizer mode trade-off (quality vs latency).
// Ref: #/components/schemas/OptimizePromptMode
type OptimizePromptMode string

const (
	OptimizePromptModeStandard OptimizePromptMode = "standard"
	OptimizePromptModeFast     OptimizePromptMode = "fast"
)

// AllValues returns all OptimizePromptMode values.
func (OptimizePromptMode) AllValues() []OptimizePromptMode {
	return []OptimizePromptMode{
		OptimizePromptModeStandard,
		OptimizePromptModeFast,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OptimizePromptMode) MarshalText() ([]byte, error) {
	switch s {
	case OptimizePromptModeStandard:
		return []byte(s), nil
	case OptimizePromptModeFast:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OptimizePromptMode) UnmarshalText(data []byte) error {
	switch OptimizePromptMode(data) {
	case OptimizePromptModeStandard:
		*s = OptimizePromptModeStandard
		return nil
	case OptimizePromptModeFast:
		*s = OptimizePromptModeFast
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/OptimizePromptOptions
type OptimizePromptOptions struct {
	// Whether the optimizer should engage its thinking pass.
	Thinking OptOptimizePromptThinking `json:"thinking"`
	// Optimizer mode trade-off (quality vs latency).
	Mode OptOptimizePromptMode `json:"mode"`
}

// GetThinking returns the value of Thinking.
func (s *OptimizePromptOptions) GetThinking() OptOptimizePromptThinking {
	return s.Thinking
}

// GetMode returns the value of Mode.
func (s *OptimizePromptOptions) GetMode() OptOptimizePromptMode {
	return s.Mode
}

// SetThinking sets the value of Thinking.
func (s *OptimizePromptOptions) SetThinking(val OptOptimizePromptThinking) {
	s.Thinking = val
}

// SetMode sets the value of Mode.
func (s *OptimizePromptOptions) SetMode(val OptOptimizePromptMode) {
	s.Mode = val
}

// Whether the prompt optimizer should engage its thinking pass.
// Ref: #/components/schemas/OptimizePromptThinking
type OptimizePromptThinking string

const (
	OptimizePromptThinkingAuto     OptimizePromptThinking = "auto"
	OptimizePromptThinkingEnabled  OptimizePromptThinking = "enabled"
	OptimizePromptThinkingDisabled OptimizePromptThinking = "disabled"
)

// AllValues returns all OptimizePromptThinking values.
func (OptimizePromptThinking) AllValues() []OptimizePromptThinking {
	return []OptimizePromptThinking{
		OptimizePromptThinkingAuto,
		OptimizePromptThinkingEnabled,
		OptimizePromptThinkingDisabled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OptimizePromptThinking) MarshalText() ([]byte, error) {
	switch s {
	case OptimizePromptThinkingAuto:
		return []byte(s), nil
	case OptimizePromptThinkingEnabled:
		return []byte(s), nil
	case OptimizePromptThinkingDisabled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OptimizePromptThinking) UnmarshalText(data []byte) error {
	switch OptimizePromptThinking(data) {
	case OptimizePromptThinkingAuto:
		*s = OptimizePromptThinkingAuto
		return nil
	case OptimizePromptThinkingEnabled:
		*s = OptimizePromptThinkingEnabled
		return nil
	case OptimizePromptThinkingDisabled:
		*s = OptimizePromptThinkingDisabled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Container/codec for the generated image bytes.
// Ref: #/components/schemas/OutputFormat
type OutputFormat string

const (
	OutputFormatJpeg OutputFormat = "jpeg"
	OutputFormatPNG  OutputFormat = "png"
)

// AllValues returns all OutputFormat values.
func (OutputFormat) AllValues() []OutputFormat {
	return []OutputFormat{
		OutputFormatJpeg,
		OutputFormatPNG,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OutputFormat) MarshalText() ([]byte, error) {
	switch s {
	case OutputFormatJpeg:
		return []byte(s), nil
	case OutputFormatPNG:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OutputFormat) UnmarshalText(data []byte) error {
	switch OutputFormat(data) {
	case OutputFormatJpeg:
		*s = OutputFormatJpeg
		return nil
	case OutputFormatPNG:
		*s = OutputFormatPNG
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// How generated image bytes are returned.
// Ref: #/components/schemas/ResponseFormat
type ResponseFormat string

const (
	ResponseFormatURL     ResponseFormat = "url"
	ResponseFormatB64JSON ResponseFormat = "b64_json"
)

// AllValues returns all ResponseFormat values.
func (ResponseFormat) AllValues() []ResponseFormat {
	return []ResponseFormat{
		ResponseFormatURL,
		ResponseFormatB64JSON,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResponseFormat) MarshalText() ([]byte, error) {
	switch s {
	case ResponseFormatURL:
		return []byte(s), nil
	case ResponseFormatB64JSON:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResponseFormat) UnmarshalText(data []byte) error {
	switch ResponseFormat(data) {
	case ResponseFormatURL:
		*s = ResponseFormatURL
		return nil
	case ResponseFormatB64JSON:
		*s = ResponseFormatB64JSON
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Whether the model may emit multiple images for one prompt.
// Ref: #/components/schemas/SequentialImageGenerationMode
type SequentialImageGenerationMode string

const (
	SequentialImageGenerationModeAuto     SequentialImageGenerationMode = "auto"
	SequentialImageGenerationModeDisabled SequentialImageGenerationMode = "disabled"
)

// AllValues returns all SequentialImageGenerationMode values.
func (SequentialImageGenerationMode) AllValues() []SequentialImageGenerationMode {
	return []SequentialImageGenerationMode{
		SequentialImageGenerationModeAuto,
		SequentialImageGenerationModeDisabled,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SequentialImageGenerationMode) MarshalText() ([]byte, error) {
	switch s {
	case SequentialImageGenerationModeAuto:
		return []byte(s), nil
	case SequentialImageGenerationModeDisabled:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SequentialImageGenerationMode) UnmarshalText(data []byte) error {
	switch SequentialImageGenerationMode(data) {
	case SequentialImageGenerationModeAuto:
		*s = SequentialImageGenerationModeAuto
		return nil
	case SequentialImageGenerationModeDisabled:
		*s = SequentialImageGenerationModeDisabled
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SequentialImageGenerationOptions
type SequentialImageGenerationOptions struct {
	// Upper bound on images returned for a single prompt.
	MaxImages OptInt32 `json:"max_images"`
}

// GetMaxImages returns the value of MaxImages.
func (s *SequentialImageGenerationOptions) GetMaxImages() OptInt32 {
	return s.MaxImages
}

// SetMaxImages sets the value of MaxImages.
func (s *SequentialImageGenerationOptions) SetMaxImages(val OptInt32) {
	s.MaxImages = val
}

// Ref: #/components/schemas/Tool
type Tool struct {
	// Tool identifier. Currently only `web_search` is supported.
	Type ToolType `json:"type"`
}

// GetType returns the value of Type.
func (s *Tool) GetType() ToolType {
	return s.Type
}

// SetType sets the value of Type.
func (s *Tool) SetType(val ToolType) {
	s.Type = val
}

// Ref: #/components/schemas/ToolType
type ToolType string

const (
	ToolTypeWebSearch ToolType = "web_search"
)

// AllValues returns all ToolType values.
func (ToolType) AllValues() []ToolType {
	return []ToolType{
		ToolTypeWebSearch,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ToolType) MarshalText() ([]byte, error) {
	switch s {
	case ToolTypeWebSearch:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ToolType) UnmarshalText(data []byte) error {
	switch ToolType(data) {
	case ToolTypeWebSearch:
		*s = ToolTypeWebSearch
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ToolUsage
type ToolUsage struct {
	// Number of web-search invocations consumed.
	WebSearch OptInt64 `json:"web_search"`
}

// GetWebSearch returns the value of WebSearch.
func (s *ToolUsage) GetWebSearch() OptInt64 {
	return s.WebSearch
}

// SetWebSearch sets the value of WebSearch.
func (s *ToolUsage) SetWebSearch(val OptInt64) {
	s.WebSearch = val
}

// Ref: #/components/schemas/Usage
type Usage struct {
	// Number of images returned in `data`.
	GeneratedImages int64 `json:"generated_images"`
	// Output tokens consumed (for prompt rewriting / reasoning).
	OutputTokens OptInt64 `json:"output_tokens"`
	// Total tokens consumed by the request.
	TotalTokens OptInt64 `json:"total_tokens"`
	// Per-tool usage breakdown.
	ToolUsage OptToolUsage `json:"tool_usage"`
}

// GetGeneratedImages returns the value of GeneratedImages.
func (s *Usage) GetGeneratedImages() int64 {
	return s.GeneratedImages
}

// GetOutputTokens returns the value of OutputTokens.
func (s *Usage) GetOutputTokens() OptInt64 {
	return s.OutputTokens
}

// GetTotalTokens returns the value of TotalTokens.
func (s *Usage) GetTotalTokens() OptInt64 {
	return s.TotalTokens
}

// GetToolUsage returns the value of ToolUsage.
func (s *Usage) GetToolUsage() OptToolUsage {
	return s.ToolUsage
}

// SetGeneratedImages sets the value of GeneratedImages.
func (s *Usage) SetGeneratedImages(val int64) {
	s.GeneratedImages = val
}

// SetOutputTokens sets the value of OutputTokens.
func (s *Usage) SetOutputTokens(val OptInt64) {
	s.OutputTokens = val
}

// SetTotalTokens sets the value of TotalTokens.
func (s *Usage) SetTotalTokens(val OptInt64) {
	s.TotalTokens = val
}

// SetToolUsage sets the value of ToolUsage.
func (s *Usage) SetToolUsage(val OptToolUsage) {
	s.ToolUsage = val
}
